## IMPORTANT: This file is generated by scripts/glue.roc
## IMPORTANT: This file is generated by scripts/glue.roc
Size := [].{

    ## Pointer-sized unsigned integer for the current target.
    ## Swap this file (or regenerate it) for wasm32 vs native.
    ## IMPORTANT: USIZE is generated by scripts/glue.roc
    USIZE : U32

    ## Godot object handle / pointer-sized value across the Roc ↔ host boundary.
    GDExtensionObjectPtr : USIZE
}