#!/usr/bin/env roc

## Generate Roc + Zig bindings from Godot's extension_api.json
app [main!] {
    roc: "nightly-2026-09-18-1d982dc",
    pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.22.2/9zUBxb1LtXYVc4eR4hAtd1WQDwBYDhM6HQdZz1UFCm2m.tar.zst"
}

import pf.Path
import pf.Stdout
import pf.Utc
import pf.OsStr

ExtensionApi : {
    header : Header,
    builtin_class_sizes : List(BuiltinClassSizes),
    builtin_class_member_offsets : List(BuiltinClassMemberOffsets),
    global_constants : List(GlobalConstant),
    global_enums : List(EnumDef),
    utility_functions : List(UtilityFunction),
    builtin_classes : List(BuiltinClass),
    classes : List(ClassDef),
    singletons : List(Singleton),
    native_structures : List(NativeStructure),
}

Header : {
    version_major : U64,
    version_minor : U64,
    version_patch : U64,
    version_status : Str,
    version_build : Str,
    version_full_name : Str,
    precision : Str,
}

BuiltinClassSizes : {
    build_configuration : Str,
    sizes : List(NamedSize),
}

NamedSize : {
    name : Str,
    size : U64,
}

BuiltinClassMemberOffsets : {
    build_configuration : Str,
    classes : List(BuiltinMemberClass),
}

BuiltinMemberClass : {
    name : Str,
    members : List(MemberOffset),
}

MemberOffset : {
    member : Str,
    offset : U64,
    meta : Try(Str, [Missing]),
}

GlobalConstant : {
    name : Str,
    value : I64,
    description : Try(Str, [Missing]),
}

EnumDef : {
    name : Str,
    is_bitfield : Try(Bool, [Missing]),
    values : List(EnumValue),
    description : Try(Str, [Missing]),
}

EnumValue : {
    name : Str,
    value : I64,
    description : Try(Str, [Missing]),
}

UtilityFunction : {
    name : Str,
    return_type : Try(Str, [Missing]),
    category : Str,
    is_vararg : Bool,
    hash : U64,
    arguments : Try(List(Argument), [Missing]),
    description : Try(Str, [Missing]),
}

Argument : {
    name : Str,
    type : Str,
    meta : Try(Str, [Missing]),
    default_value : Try(Str, [Missing]),
}

MethodDef : {
    name : Str,
    is_const : Bool,
    is_static : Bool,
    is_vararg : Bool,
    is_virtual : Try(Bool, [Missing]),
    hash : U64,
    hash_compatibility : Try(List(U64), [Missing]),
    return_type : Try(Str, [Missing]),
    return_value : Try(ReturnValue, [Missing]),
    arguments : Try(List(Argument), [Missing]),
    description : Try(Str, [Missing]),
}

ReturnValue : {
    type : Str,
    meta : Try(Str, [Missing]),
}

PropertyDef : {
    type : Str,
    name : Str,
    meta : Try(Str, [Missing]),
    getter : Try(Str, [Missing]),
    setter : Try(Str, [Missing]),
    description : Try(Str, [Missing]),
}

SignalDef : {
    name : Str,
    arguments : Try(List(Argument), [Missing]),
    description : Try(Str, [Missing]),
}

BuiltinClass : {
    name : Str,
    is_keyed : Bool,
    has_destructor : Bool,
    indexing_return_type : Try(Str, [Missing]),
    brief_description : Try(Str, [Missing]),
    description : Try(Str, [Missing]),
    members : Try(List(PropertyDef), [Missing]),
    constants : Try(List(NamedValue), [Missing]),
    enums : Try(List(EnumDef), [Missing]),
    operators : List(OperatorDef),
    methods : Try(List(MethodDef), [Missing]),
    constructors : List(ConstructorDef),
}

NamedValue : {
    name : Str,
    type : Str,
    value : Str,
    description : Try(Str, [Missing]),
}

OperatorDef : {
    name : Str,
    right_type : Try(Str, [Missing]),
    return_type : Try(Str, [Missing]),
    description : Try(Str, [Missing]),
}

ConstructorDef : {
    index : U64,
    arguments : Try(List(Argument), [Missing]),
    description : Try(Str, [Missing]),
}

ClassDef : {
    name : Str,
    is_refcounted : Bool,
    is_instantiable : Bool,
    inherits : Try(Str, [Missing]),
    api_type : Str,
    brief_description : Try(Str, [Missing]),
    description : Try(Str, [Missing]),
    enums : Try(List(EnumDef), [Missing]),
    methods : Try(List(MethodDef), [Missing]),
    properties : Try(List(PropertyDef), [Missing]),
    signals : Try(List(SignalDef), [Missing]),
}

Singleton : {
    name : Str,
    type : Str,
}

NativeStructure : {
    name : Str,
    format : Str,
}

main! : List(OsStr) => Try({}, _)
main! = |_args| {

    source : Path
    source = "vendor/godot/extension_api.json"

    roc_out_path : Path
    roc_out_path = "platform/gen"

    Stdout.line!(
        \\#
        \\# Generated by scripts/extension_api.generate.roc
        \\# from ${Str.inspect(source)} → ${Str.inspect(roc_out_path)}
        \\#
    )?

    read_start = Utc.now!()
    json_contents = source.read_utf8!()?
    Stdout.line!("# Read: ${(Utc.now!() - read_start).to_str()}ns")?

    parse_start = Utc.now!()
    decoded : ExtensionApi
    decoded = Json.parse(json_contents)?
    Stdout.line!("# Parse: ${(Utc.now!() - parse_start).to_str()}ns")?

    Stdout.line!("${render_header(decoded)}")?

    t0 = Utc.now!()
    Path.join(roc_out_path, "Host.roc").write_utf8!(host_to_roc_source_str(decoded))?
    Path.join(roc_out_path, "engine/GlobalConstants.roc").write_utf8!(global_constants_to_roc_source_str(decoded))?
    Path.join(roc_out_path, "engine/GlobalEnums.roc").write_utf8!(global_enums_to_roc_source_str(decoded))?
    Path.join(roc_out_path, "engine/BuiltinClassSizes.roc").write_utf8!(builtin_class_sizes_to_roc_source_str(decoded))?
    Path.join(roc_out_path, "engine/BuiltinClassMemberOffsets.roc").write_utf8!(builtin_class_member_offsets_to_roc_source_str(decoded))?
    Path.join(roc_out_path, "engine/NativeStructures.roc").write_utf8!(native_structures_to_roc_source_str(decoded))?
    Path.join(roc_out_path, "engine/UtilityFunctions.roc").write_utf8!(utility_functions_to_roc_source_str(decoded))?
    Stdout.line!("# meta+Host: ${(Utc.now!() - t0).to_str()}ns")?

    t1 = Utc.now!()
    for bic in decoded.builtin_classes {
        mod_name = builtin_module_name(bic.name)
        Path.join(roc_out_path, "engine/builtin_classes/${mod_name}.roc")
            .write_utf8!(builtin_class_to_roc_source_str(bic))?
    }
    Stdout.line!("# builtins: ${(Utc.now!() - t1).to_str()}ns")?

    t2 = Utc.now!()
    for cls in decoded.classes {
        mod_name = class_module_name(cls.name)
        Path.join(roc_out_path, "engine/classes/${mod_name}.roc")
            .write_utf8!(class_to_roc_source_str(cls))?
    }
    Stdout.line!("# classes: ${(Utc.now!() - t2).to_str()}ns")?

    t3 = Utc.now!()
    for s in decoded.singletons {
        mod_name = singleton_module_name(s.name)
        Path.join(roc_out_path, "engine/singletons/${mod_name}.roc")
            .write_utf8!(singleton_to_roc_source_str(s))?
    }
    Stdout.line!("# singletons: ${(Utc.now!() - t3).to_str()}ns")?

    Path.join(roc_out_path, "main.roc").write_utf8!(gen_package_main_roc(decoded))?

    t4 = Utc.now!()
    Path.join("src", "zig_platform_abi_impl.zig")
        .write_utf8!(zig_platform_abi_impl_to_str(decoded))?
    Stdout.line!("# zig abi: ${(Utc.now!() - t4).to_str()}ns")?

    Stdout.line!("# total after parse: ${(Utc.now!() - parse_start).to_str()}ns")?
    Ok({})
}

# =============================================================================
# Naming
# =============================================================================

builtin_module_name : Str -> Str
builtin_module_name = |name| {
    match name {
        "bool" => "GodotBool"
        "int" => "GodotInt"
        "float" => "GodotFloat"
        other => other
    }
}

class_module_name : Str -> Str
class_module_name = |name| {
    match name {
        "Crypto" => "GodotCrypto"
        "Range" => "GodotRange"
        other => other
    }
}

singleton_module_name : Str -> Str
singleton_module_name = |name| "${name}Singleton"

roc_type_ident : Str -> Str
roc_type_ident = |s|
    s.replace_each("::", "_").replace_each(".", "_").replace_each(" ", "_").replace_each("/", "_")

to_value_name : Str -> Str
to_value_name = |s| s.with_ascii_lowercased()

## Sanitize Godot method/property names into Roc/Zig-safe identifiers
roc_fn_name : Str -> Str
roc_fn_name = |name| {
    n =
        name
            .replace_each(" ", "_")
            .replace_each(".", "_")
            .replace_each(":", "_")
            .replace_each("/", "_")
            .replace_each("-", "_")
            .replace_each("==", "eq")
            .replace_each("!=", "neq")
            .replace_each("<=", "lte")
            .replace_each(">=", "gte")
            .replace_each("<", "lt")
            .replace_each(">", "gt")
            .replace_each("*", "mul")
            .replace_each("/", "div")
            .replace_each("+", "add")
            .replace_each("%", "mod")
            .replace_each("^", "xor")
            .replace_each("|", "bitor")
            .replace_each("&", "bitand")
            .replace_each("!", "not")
    # leading underscore stays (virtuals); ensure not empty
    if n == "" {
        "op"
    } else {
        n
    }
}

host_method_symbol : Str, U64 -> Str
host_method_symbol = |name, hash| "${roc_fn_name(name)}_${hash.to_str()}"

c_to_roc_type : Str -> Str
c_to_roc_type = |str| {
    # strip enum:: / bitfield:: prefixes for display types
    cleaned =
        if str.starts_with("enum::") {
            roc_type_ident(str.drop_prefix("enum::"))
        } else if str.starts_with("bitfield::") {
            roc_type_ident(str.drop_prefix("bitfield::"))
        } else {
            str
        }
    match cleaned {
        "int" => "I32"
        "float" => "F32"
        "double" => "F64"
        "bool" => "Bool"
        "void" => "{}"
        "Crypto" => "GodotCrypto"
        "Range" => "GodotRange"
        other => builtin_module_name(other)
    }
}

## C return type for Zig stubs (coarse)
c_to_zig_ret : Str -> Str
c_to_zig_ret = |str| {
    match str {
        "bool" => "u8"
        "int" => "i64"
        "float" => "f64"
        "double" => "f64"
        "void" => "void"
        _ => "void" # complex / object: out-param later
    }
}

c_to_zig_ret_from_try : Try(Str, [Missing]) -> Str
c_to_zig_ret_from_try = |maybe|
    match maybe {
        Ok(t) => c_to_zig_ret(t)
        _ => "void"
    }

# =============================================================================
# Package root
# =============================================================================

gen_package_main_roc : ExtensionApi -> Str
gen_package_main_roc = |eapi| {

    builtin_names = eapi.builtin_classes.map(|b| builtin_module_name(b.name))
    class_names = eapi.classes.map(|c| class_module_name(c.name))
    singleton_names = eapi.singletons.map(|s| singleton_module_name(s.name))

    meta_names = [
        "Host",
        "GlobalConstants",
        "GlobalEnums",
        "BuiltinClassSizes",
        "BuiltinClassMemberOffsets",
        "NativeStructures",
        "UtilityFunctions",
    ]

    all_names =
        List.concat(meta_names, List.concat(builtin_names, List.concat(class_names, singleton_names)))

    expose = Str.join_with(all_names.map(|n| "    ${n}"), ",\n")

    meta_imports =
        \\import Host as Host
        \\import engine/GlobalConstants as GlobalConstants
        \\import engine/GlobalEnums as GlobalEnums
        \\import engine/BuiltinClassSizes as BuiltinClassSizes
        \\import engine/BuiltinClassMemberOffsets as BuiltinClassMemberOffsets
        \\import engine/NativeStructures as NativeStructures
        \\import engine/UtilityFunctions as UtilityFunctions

    builtin_imports =
        Str.join_with(builtin_names.map(|n| "import engine/builtin_classes/${n} as ${n}"), "\n")
    class_imports =
        Str.join_with(class_names.map(|n| "import engine/classes/${n} as ${n}"), "\n")
    singleton_imports =
        Str.join_with(singleton_names.map(|n| "import engine/singletons/${n} as ${n}"), "\n")

    \\# AUTO-GENERATED — do not edit
    \\package [
    \\${expose}
    \\] {}
    \\
    \\${meta_imports}
    \\
    \\${builtin_imports}
    \\
    \\${class_imports}
    \\
    \\${singleton_imports}
    \\
}

render_header : ExtensionApi -> Str
render_header = |eapi|
    \\# ${eapi.header.version_full_name}
    \\# builtins=${eapi.builtin_classes.len().to_str()} classes=${eapi.classes.len().to_str()} singletons=${eapi.singletons.len().to_str()}

# =============================================================================
# Shared method / property rendering (Roc)
# =============================================================================

method_arg_types : MethodDef -> Str
method_arg_types = |md|
    match md.arguments {
        Ok(args) if !(args.is_empty()) =>
            Str.join_with(args.map(|a| c_to_roc_type(a.type)), ", ")
        _ => "()"
    }

method_arg_names : MethodDef -> Str
method_arg_names = |md|
    match md.arguments {
        Ok(args) if !(args.is_empty()) =>
            Str.join_with(args.map(|a| a.name), ", ")
        _ => ""
    }

method_return_type : MethodDef -> Str
method_return_type = |md|
    match md.return_type {
        Ok(rt) => c_to_roc_type(rt)
        _ =>
            match md.return_value {
                Ok(rv) => c_to_roc_type(rv.type)
                _ => "{}"
            }
    }

## Live Roc method binding → Host.<name>_<hash>!
method_def_live : MethodDef -> Str
method_def_live = |md| {
    fn = roc_fn_name(md.name)
    sym = host_method_symbol(md.name, md.hash)
    args_ty = method_arg_types(md)
    args_ns = method_arg_names(md)
    ret = method_return_type(md)
    lambda =
        if args_ns == "" {
            "|_| Host.${sym}!"
        } else {
            "|${args_ns}| Host.${sym}!(${args_ns})"
        }
    \\    ${fn}! : ${args_ty} -> ${ret}
    \\    ${fn}! = ${lambda}
}

## Property → get_* / set_* using API getter/setter names when present
property_defs_live : PropertyDef -> Str
property_defs_live = |p| {
    ty = c_to_roc_type(p.type)
    getter_fn =
        match p.getter {
            Ok(g) => roc_fn_name(g)
            _ => "get_${roc_fn_name(p.name)}"
        }
    setter_fn =
        match p.setter {
            Ok(s) => roc_fn_name(s)
            _ => "set_${roc_fn_name(p.name)}"
        }
    # Host symbols for props use getter/setter name + synthetic tag "prop" (no hash in API)
    # Prefer real method hashes when methods list has matching names; else name_prop
    get_sym = "${getter_fn}_prop"
    set_sym = "${setter_fn}_prop"
    getter_block =
        match p.getter {
            Ok(_) | Err(Missing) =>
                \\    ${getter_fn}! : () -> ${ty}
                \\    ${getter_fn}! = |_| Host.${get_sym}!
            _ => ""
        }
    # Always emit getter line when we have a type; setter only if setter present
    setter_block =
        match p.setter {
            Ok(_) =>
                \\    ${setter_fn}! : ${ty} -> {}
                \\    ${setter_fn}! = |v| Host.${set_sym}!(v)
            _ => ""
        }
    \\    # property ${p.name} : ${ty}
    \\${getter_block}
    \\${setter_block}
}

methods_block_live : Try(List(MethodDef), [Missing]) -> Str
methods_block_live = |maybe|
    match maybe {
        Ok(ms) => Str.join_with(ms.map(method_def_live), "\n")
        _ => ""
    }

properties_block_live : Try(List(PropertyDef), [Missing]) -> Str
properties_block_live = |maybe|
    match maybe {
        Ok(ps) => Str.join_with(ps.map(property_defs_live), "\n")
        _ => ""
    }

enum_def_line : EnumDef -> Str
enum_def_line = |e| {
    ename = roc_type_ident(e.name)
    values = Str.join_with(e.values.map(|v| v.name), ", ")
    \\    ${ename} : [${values}]
}

enums_block : Try(List(EnumDef), [Missing]) -> Str
enums_block = |maybe|
    match maybe {
        Ok(ens) => Str.join_with(ens.map(enum_def_line), "\n")
        _ => ""
    }

signal_def_line : SignalDef -> Str
signal_def_line = |sig| {
    args =
        match sig.arguments {
            Ok(a) if !(a.is_empty()) =>
                Str.join_with(a.map(|x| "${x.name} : ${c_to_roc_type(x.type)}"), ", ")
            _ => "()"
        }
    \\    # signal ${sig.name} : ${args}
}

signals_block : Try(List(SignalDef), [Missing]) -> Str
signals_block = |maybe|
    match maybe {
        Ok(ss) => Str.join_with(ss.map(signal_def_line), "\n")
        _ => ""
    }

# =============================================================================
# Host.roc — declarations for every util, method, property get/set
# =============================================================================

host_method_decl : Str, MethodDef -> Str
host_method_decl = |owner, md| {
    sym = host_method_symbol(md.name, md.hash)
    args_ty = method_arg_types(md)
    ret = method_return_type(md)
    \\    # ${owner}.${md.name}
    \\    ${sym}! : ${args_ty} -> ${ret}
}

host_property_decls : Str, PropertyDef -> Str
host_property_decls = |_owner, p| {
    ty = c_to_roc_type(p.type)
    getter_fn =
        match p.getter {
            Ok(g) => roc_fn_name(g)
            _ => "get_${roc_fn_name(p.name)}"
        }
    setter_fn =
        match p.setter {
            Ok(s) => roc_fn_name(s)
            _ => "set_${roc_fn_name(p.name)}"
        }
    get_line =
        \\    ${getter_fn}_prop! : () -> ${ty}
    set_line =
        match p.setter {
            Ok(_) =>
                \\    ${setter_fn}_prop! : ${ty} -> {}
            _ => ""
        }
    \\${get_line}
    \\${set_line}
}

host_to_roc_source_str : ExtensionApi -> Str
host_to_roc_source_str = |eapi| {

    util_decls =
        Str.join_with(
            eapi.utility_functions.map(|uf| {
                ret =
                    match uf.return_type {
                        Ok(rt) => c_to_roc_type(rt)
                        _ => "{}"
                    }
                args =
                    match uf.arguments {
                        Ok(a) if !(a.is_empty()) =>
                            Str.join_with(a.map(|x| c_to_roc_type(x.type)), ", ")
                        _ => "()"
                    }
                sym = "util_${roc_fn_name(uf.name)}_${uf.hash.to_str()}"
                \\    ${sym}! : ${args} -> ${ret}
            }),
            "\n",
        )

    sing_decls =
        Str.join_with(
            eapi.singletons.map(|s|
                \\    get_singleton_${roc_fn_name(s.name)}! : () -> U64
            ),
            "\n",
        )

    builtin_method_decls =
        Str.join_with(
            eapi.builtin_classes.map(|bic| {
                match bic.methods {
                    Ok(ms) =>
                        Str.join_with(ms.map(|md| host_method_decl(bic.name, md)), "\n")
                    _ => ""
                }
            }),
            "\n",
        )

    class_method_decls =
        Str.join_with(
            eapi.classes.map(|cls| {
                match cls.methods {
                    Ok(ms) =>
                        Str.join_with(ms.map(|md| host_method_decl(cls.name, md)), "\n")
                    _ => ""
                }
            }),
            "\n",
        )

    class_prop_decls =
        Str.join_with(
            eapi.classes.map(|cls| {
                match cls.properties {
                    Ok(ps) =>
                        Str.join_with(ps.map(|p| host_property_decls(cls.name, p)), "\n")
                    _ => ""
                }
            }),
            "\n",
        )

    \\# AUTO-GENERATED Host surface — wire via roc glue / Zig exports
    \\# Symbols match src/zig_platform_abi_impl.zig (godot_roc_*).
    \\Host := {
    \\}.{
    \\    # --- singletons ---
    \\${sing_decls}
    \\
    \\    # --- utility functions ---
    \\${util_decls}
    \\
    \\    # --- builtin class methods ---
    \\${builtin_method_decls}
    \\
    \\    # --- engine class methods ---
    \\${class_method_decls}
    \\
    \\    # --- engine class property get/set ---
    \\${class_prop_decls}
    \\}
}

# =============================================================================
# Meta modules
# =============================================================================

global_constants_to_roc_source_str : ExtensionApi -> Str
global_constants_to_roc_source_str = |eapi| {
    body =
        Str.join_with(
            eapi.global_constants.map(|gc| {
                vn = to_value_name(gc.name)
                \\    ${vn} : I64
                \\    ${vn} = ${gc.value.to_str()}
            }),
            "\n",
        )
    \\# AUTO-GENERATED
    \\GlobalConstants := {
    \\}.{
    \\${body}
    \\}
}

global_enums_to_roc_source_str : ExtensionApi -> Str
global_enums_to_roc_source_str = |eapi| {
    body =
        Str.join_with(
            eapi.global_enums.map(|e| {
                ename = roc_type_ident(e.name)
                values = Str.join_with(e.values.map(|v| v.name), ", ")
                notes =
                    Str.join_with(
                        e.values.map(|v| "    # ${ename}_${v.name} = ${v.value.to_str()}"),
                        "\n",
                    )
                \\    ${ename} : [${values}]
                \\${notes}
            }),
            "\n",
        )
    \\# AUTO-GENERATED
    \\GlobalEnums := {
    \\}.{
    \\${body}
    \\}
}

builtin_class_sizes_to_roc_source_str : ExtensionApi -> Str
builtin_class_sizes_to_roc_source_str = |eapi| {
    body =
        Str.join_with(
            eapi.builtin_class_sizes.map(|bcs| {
                lines =
                    Str.join_with(
                        bcs.sizes.map(|ns| "    # ${ns.name} = ${ns.size.to_str()}"),
                        "\n",
                    )
                \\    # ${bcs.build_configuration}
                \\${lines}
            }),
            "\n",
        )
    \\BuiltinClassSizes := {
    \\}.{
    \\${body}
    \\}
}

builtin_class_member_offsets_to_roc_source_str : ExtensionApi -> Str
builtin_class_member_offsets_to_roc_source_str = |eapi| {
    body =
        Str.join_with(
            eapi.builtin_class_member_offsets.map(|bco| {
                classes =
                    Str.join_with(
                        bco.classes.map(|bc| {
                            ms =
                                Str.join_with(
                                    bc.members.map(|m| "    #   ${m.member} @ ${m.offset.to_str()}"),
                                    "\n",
                                )
                            \\    # ${bc.name}
                            \\${ms}
                        }),
                        "\n",
                    )
                \\    # ${bco.build_configuration}
                \\${classes}
            }),
            "\n",
        )
    \\BuiltinClassMemberOffsets := {
    \\}.{
    \\${body}
    \\}
}

native_structures_to_roc_source_str : ExtensionApi -> Str
native_structures_to_roc_source_str = |eapi| {
    body =
        Str.join_with(
            eapi.native_structures.map(|ns| "    # ${ns.name}: ${ns.format}"),
            "\n",
        )
    \\NativeStructures := {
    \\}.{
    \\${body}
    \\}
}

utility_functions_to_roc_source_str : ExtensionApi -> Str
utility_functions_to_roc_source_str = |eapi| {
    body =
        Str.join_with(
            eapi.utility_functions.map(|uf| {
                ret =
                    match uf.return_type {
                        Ok(rt) => c_to_roc_type(rt)
                        _ => "{}"
                    }
                args =
                    match uf.arguments {
                        Ok(a) if !(a.is_empty()) =>
                            Str.join_with(a.map(|x| c_to_roc_type(x.type)), ", ")
                        _ => "()"
                    }
                fn = roc_fn_name(uf.name)
                sym = "util_${fn}_${uf.hash.to_str()}"
                \\    ${fn}! : ${args} -> ${ret}
                \\    ${fn}! = Host.${sym}!
            }),
            "\n",
        )
    \\UtilityFunctions := {
    \\}.{
    \\${body}
    \\}
}

# =============================================================================
# Builtin classes
# =============================================================================

builtin_class_to_roc_source_str : BuiltinClass -> Str
builtin_class_to_roc_source_str = |bic| {

    type_name = builtin_module_name(bic.name)

    members_list =
        match bic.members {
            Ok(ms) => ms
            _ => []
        }

    has_members = !(members_list.is_empty())

    unique =
        members_list.map(|m| c_to_roc_type(m.type)).fold(
            [],
            |acc, t| {
                is_prim =
                    match t {
                        "I32" | "F32" | "F64" | "Bool" | "{}" | "U64" => Bool.True
                        _ => Bool.False
                    }
                if is_prim {
                    acc
                } else {
                    if t == type_name {
                        acc
                    } else {
                        if List.contains(acc, t) {
                            acc
                        } else {
                            List.append(acc, t)
                        }
                    }
                }
            },
        )

    import_lines =
        Str.join_with(unique.map(|t| "import ${t} as ${t}"), "\n")

    members_str =
        if has_members {
            Str.join_with(members_list.map(|m| "    ${m.name} : ${c_to_roc_type(m.type)}"), ",\n")
        } else {
            "    ptr : U64"
        }

    construct_sig =
        if has_members {
            arg_tys = Str.join_with(members_list.map(|m| c_to_roc_type(m.type)), ", ")
            arg_ns = Str.join_with(members_list.map(|m| m.name), ", ")
            \\    construct_default! : ${arg_tys} -> ${type_name}
            \\    construct_default! = |${arg_ns}| { { ${arg_ns} } }
        } else {
            \\    construct_default! : {} -> ${type_name}
            \\    construct_default! = |_| { { ptr: 0 } }
        }

    constructors_str =
        Str.join_with(
            bic.constructors
                .keep_if(|c| c.arguments != Err(Missing))
                .map(|c| {
                    arg_types =
                        match c.arguments {
                            Ok(args) => Str.join_with(args.map(|a| c_to_roc_type(a.type)), ", ")
                            _ => ""
                        }
                    \\    # construct_${c.index.to_str()}! : ${arg_types} -> ${type_name}
                }),
            "\n",
        )

    constants_str =
        match bic.constants {
            Ok(cs) =>
                Str.join_with(
                    cs.map(|c| {
                        vn = to_value_name(c.name)
                        vs =
                            c.value
                                .replace_first(bic.name, "construct_default!")
                                .replace_each("inf", "F32.infinity")
                        \\    # ${vn} = ${vs}
                    }),
                    "\n",
                )
            _ => ""
        }

    operators_str =
        Str.join_with(
            bic.operators.map(|op| "    # op ${op.name}"),
            "\n",
        )

    imports_section =
        if import_lines == "" {
            ""
        } else {
            "${import_lines}\n\n"
        }

    \\# builtin ${bic.name} → ${type_name}
    \\${imports_section}${type_name} := {
    \\${members_str}
    \\}.{
    \\${construct_sig}
    \\${constructors_str}
    \\${constants_str}
    \\${enums_block(bic.enums)}
    \\
    \\    # --- methods ---
    \\${methods_block_live(bic.methods)}
    \\
    \\${operators_str}
    \\}
}

# =============================================================================
# Engine classes
# =============================================================================

class_to_roc_source_str : ClassDef -> Str
class_to_roc_source_str = |cls| {
    type_name = class_module_name(cls.name)
    inherits_line =
        match cls.inherits {
            Ok(p) => "# inherits: ${p}\n"
            _ => ""
        }
    \\# class ${cls.name} → ${type_name}
    \\${inherits_line}${type_name} := {
    \\    ptr : U64,
    \\}.{
    \\${enums_block(cls.enums)}
    \\
    \\    # --- properties (get_* / set_*) ---
    \\${properties_block_live(cls.properties)}
    \\
    \\    # --- methods ---
    \\${methods_block_live(cls.methods)}
    \\
    \\${signals_block(cls.signals)}
    \\}
}

singleton_to_roc_source_str : Singleton -> Str
singleton_to_roc_source_str = |st| {
    mod_name = singleton_module_name(st.name)
    \\# singleton ${st.name} → ${mod_name}
    \\${mod_name} := {
    \\    ptr : U64,
    \\}.{
    \\    get! : () -> ${mod_name}
    \\    get! = |_| { { ptr: Host.get_singleton_${roc_fn_name(st.name)}!() } }
    \\}
}

# =============================================================================
# Zig C-ABI: utils, singletons, builtin methods, class methods, properties
# =============================================================================

zig_export_method : Str, MethodDef -> Str
zig_export_method = |owner, md| {
    sym = host_method_symbol(md.name, md.hash)
    c_name = "godot_roc_${sym}"
    ret =
        match md.return_type {
            Ok(t) => c_to_zig_ret(t)
            _ =>
                match md.return_value {
                    Ok(rv) => c_to_zig_ret(rv.type)
                    _ => "void"
                }
        }
    default_ret =
        match ret {
            "u8" => "return 0;"
            "i64" => "return 0;"
            "f64" => "return 0;"
            _ => ""
        }
    \\
    \\/// ${owner}.${md.name}  hash=${md.hash.to_str()}
    \\export fn ${c_name}() callconv(.c) ${ret} {
    \\    // TODO: getMethodBind("${owner}", "${md.name}", ${md.hash.to_str()}); ptrcall(...)
    \\    ${default_ret}
    \\}
}

zig_export_property : Str, PropertyDef -> Str
zig_export_property = |owner, p| {
    ty = p.type
    zig_ty = c_to_zig_ret(ty)
    getter_fn =
        match p.getter {
            Ok(g) => roc_fn_name(g)
            _ => "get_${roc_fn_name(p.name)}"
        }
    setter_fn =
        match p.setter {
            Ok(s) => roc_fn_name(s)
            _ => "set_${roc_fn_name(p.name)}"
        }
    get_default =
        match zig_ty {
            "u8" => "return 0;"
            "i64" => "return 0;"
            "f64" => "return 0;"
            _ => ""
        }
    get_fn =
        \\
        \\/// ${owner} property ${p.name} getter
        \\export fn godot_roc_${getter_fn}_prop() callconv(.c) ${zig_ty} {
        \\    // TODO: method bind for ${getter_fn} on ${owner}
        \\    ${get_default}
        \\}
    set_fn =
        match p.setter {
            Ok(_) =>
                \\
                \\/// ${owner} property ${p.name} setter
                \\export fn godot_roc_${setter_fn}_prop() callconv(.c) void {
                \\    // TODO: method bind for ${setter_fn} on ${owner}
                \\}
            _ => ""
        }
    "${get_fn}${set_fn}"
}

zig_platform_abi_impl_to_str : ExtensionApi -> Str
zig_platform_abi_impl_to_str = |eapi| {

    utils =
        Str.join_with(
            eapi.utility_functions.map(|uf| {
                sym = "util_${roc_fn_name(uf.name)}_${uf.hash.to_str()}"
                ret = c_to_zig_ret_from_try(uf.return_type)
                default_ret =
                    match ret {
                        "u8" => "return 0;"
                        "i64" => "return 0;"
                        "f64" => "return 0;"
                        _ => ""
                    }
                \\
                \\export fn godot_roc_${sym}() callconv(.c) ${ret} {
                \\    // TODO: utility ${uf.name} hash ${uf.hash.to_str()}
                \\    ${default_ret}
                \\}
            }),
            "\n",
        )

    sings =
        Str.join_with(
            eapi.singletons.map(|s|
                \\
                \\export fn godot_roc_get_singleton_${roc_fn_name(s.name)}() callconv(.c) u64 {
                \\    return 0; // TODO singleton ${s.name}
                \\}
            ),
            "\n",
        )

    builtin_methods =
        Str.join_with(
            eapi.builtin_classes.map(|bic| {
                match bic.methods {
                    Ok(ms) =>
                        Str.join_with(ms.map(|md| zig_export_method(bic.name, md)), "\n")
                    _ => ""
                }
            }),
            "\n",
        )

    class_methods =
        Str.join_with(
            eapi.classes.map(|cls| {
                match cls.methods {
                    Ok(ms) =>
                        Str.join_with(ms.map(|md| zig_export_method(cls.name, md)), "\n")
                    _ => ""
                }
            }),
            "\n",
        )

    class_props =
        Str.join_with(
            eapi.classes.map(|cls| {
                match cls.properties {
                    Ok(ps) =>
                        Str.join_with(ps.map(|p| zig_export_property(cls.name, p)), "\n")
                    _ => ""
                }
            }),
            "\n",
        )

    \\//! AUTO-GENERATED by scripts/extension_api.generate.roc
    \\//! C-ABI for Roc Host (roc glue). Implement TODO bodies with GDExtension ptrcalls.
    \\//!
    \\//! Naming:
    \\//!   Host.<fn>_<hash>!     ↔  export fn godot_roc_<fn>_<hash>
    \\//!   Host.<get>_prop!      ↔  export fn godot_roc_<get>_prop
    \\//!   Host.util_<fn>_<hash>! ↔ export fn godot_roc_util_<fn>_<hash>
    \\
    \\const std = @import("std");
    \\
    \\// ---------------------------------------------------------------------------
    \\// Singletons
    \\// ---------------------------------------------------------------------------
    \\${sings}
    \\
    \\// ---------------------------------------------------------------------------
    \\// @GlobalScope utilities
    \\// ---------------------------------------------------------------------------
    \\${utils}
    \\
    \\// ---------------------------------------------------------------------------
    \\// Builtin class methods
    \\// ---------------------------------------------------------------------------
    \\${builtin_methods}
    \\
    \\// ---------------------------------------------------------------------------
    \\// Engine class methods
    \\// ---------------------------------------------------------------------------
    \\${class_methods}
    \\
    \\// ---------------------------------------------------------------------------
    \\// Engine class properties (get_* / set_*)
    \\// ---------------------------------------------------------------------------
    \\${class_props}
    \\
}
