#!/usr/bin/env roc

## Generate Roc + Zig bindings from Godot's extension_api.json
app [main!] {
    roc: "nightly-2026-09-18-1d982dc",
    pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.22.2/9zUBxb1LtXYVc4eR4hAtd1WQDwBYDhM6HQdZz1UFCm2m.tar.zst"
}

import pf.Path
import pf.Stdout
import pf.Utc
import pf.OsStr

ExtensionApi : {
    header : Header,
    builtin_class_sizes : List(BuiltinClassSizes),
    builtin_class_member_offsets : List(BuiltinClassMemberOffsets),
    global_constants : List(GlobalConstant),
    global_enums : List(EnumDef),
    utility_functions : List(UtilityFunction),
    builtin_classes : List(BuiltinClass),
    classes : List(ClassDef),
    singletons : List(Singleton),
    native_structures : List(NativeStructure),
}

Header : {
    version_major : U64,
    version_minor : U64,
    version_patch : U64,
    version_status : Str,
    version_build : Str,
    version_full_name : Str,
    precision : Str,
}

BuiltinClassSizes : {
    build_configuration : Str,
    sizes : List(NamedSize),
}

NamedSize : {
    name : Str,
    size : U64,
}

BuiltinClassMemberOffsets : {
    build_configuration : Str,
    classes : List(BuiltinMemberClass),
}

BuiltinMemberClass : {
    name : Str,
    members : List(MemberOffset),
}

MemberOffset : {
    member : Str,
    offset : U64,
    meta : Try(Str, [Missing]),
}

GlobalConstant : {
    name : Str,
    value : I64,
    description : Try(Str, [Missing]),
}

EnumDef : {
    name : Str,
    is_bitfield : Try(Bool, [Missing]),
    values : List(EnumValue),
    description : Try(Str, [Missing]),
}

EnumValue : {
    name : Str,
    value : I64,
    description : Try(Str, [Missing]),
}

UtilityFunction : {
    name : Str,
    return_type : Try(Str, [Missing]),
    category : Str,
    is_vararg : Bool,
    hash : U64,
    arguments : Try(List(Argument), [Missing]),
    description : Try(Str, [Missing]),
}

Argument : {
    name : Str,
    type : Str,
    meta : Try(Str, [Missing]),
    default_value : Try(Str, [Missing]),
}

MethodDef : {
    name : Str,
    is_const : Bool,
    is_static : Bool,
    is_vararg : Bool,
    is_virtual : Try(Bool, [Missing]),
    hash : U64,
    hash_compatibility : Try(List(U64), [Missing]),
    return_type : Try(Str, [Missing]),
    return_value : Try(ReturnValue, [Missing]),
    arguments : Try(List(Argument), [Missing]),
    description : Try(Str, [Missing]),
}

ReturnValue : {
    type : Str,
    meta : Try(Str, [Missing]),
}

PropertyDef : {
    type : Str,
    name : Str,
    meta : Try(Str, [Missing]),
    getter : Try(Str, [Missing]),
    setter : Try(Str, [Missing]),
    description : Try(Str, [Missing]),
}

SignalDef : {
    name : Str,
    arguments : Try(List(Argument), [Missing]),
    description : Try(Str, [Missing]),
}

BuiltinClass : {
    name : Str,
    is_keyed : Bool,
    has_destructor : Bool,
    indexing_return_type : Try(Str, [Missing]),
    brief_description : Try(Str, [Missing]),
    description : Try(Str, [Missing]),
    members : Try(List(PropertyDef), [Missing]),
    constants : Try(List(NamedValue), [Missing]),
    enums : Try(List(EnumDef), [Missing]),
    operators : List(OperatorDef),
    methods : Try(List(MethodDef), [Missing]),
    constructors : List(ConstructorDef),
}

NamedValue : {
    name : Str,
    type : Str,
    value : Str,
    description : Try(Str, [Missing]),
}

OperatorDef : {
    name : Str,
    right_type : Try(Str, [Missing]),
    return_type : Try(Str, [Missing]),
    description : Try(Str, [Missing]),
}

ConstructorDef : {
    index : U64,
    arguments : Try(List(Argument), [Missing]),
    description : Try(Str, [Missing]),
}

ClassDef : {
    name : Str,
    is_refcounted : Bool,
    is_instantiable : Bool,
    inherits : Try(Str, [Missing]),
    api_type : Str,
    brief_description : Try(Str, [Missing]),
    description : Try(Str, [Missing]),
    enums : Try(List(EnumDef), [Missing]),
    methods : Try(List(MethodDef), [Missing]),
    properties : Try(List(PropertyDef), [Missing]),
    signals : Try(List(SignalDef), [Missing]),
}

Singleton : {
    name : Str,
    type : Str,
}

NativeStructure : {
    name : Str,
    format : Str,
}

main! : List(OsStr) => Try({}, _)
main! = |_args| {

    source : Path
    source = "vendor/godot/extension_api.json"

    roc_out_path : Path
    roc_out_path = "platform/gen"

    Stdout.line!(
        \\#
        \\# Generated by scripts/extension_api.generate.roc
        \\# from ${Str.inspect(source)} → ${Str.inspect(roc_out_path)}
        \\#
    )?

    read_start = Utc.now!()
    json_contents = source.read_utf8!()?
    Stdout.line!("# Read: ${(Utc.now!() - read_start).to_str()}ns")?

    parse_start = Utc.now!()
    decoded : ExtensionApi
    decoded = Json.parse(json_contents)?
    Stdout.line!("# Parse: ${(Utc.now!() - parse_start).to_str()}ns")?

    Stdout.line!("${render_header(decoded)}")?

    Path.join(roc_out_path, "Host.roc").write_utf8!(host_to_roc_source_str(decoded))?
    Path.join(roc_out_path, "engine/GlobalConstants.roc").write_utf8!(global_constants_to_roc_source_str(decoded))?
    Path.join(roc_out_path, "engine/GlobalEnums.roc").write_utf8!(global_enums_to_roc_source_str(decoded))?
    Path.join(roc_out_path, "engine/BuiltinClassSizes.roc").write_utf8!(builtin_class_sizes_to_roc_source_str(decoded))?
    Path.join(roc_out_path, "engine/BuiltinClassMemberOffsets.roc").write_utf8!(builtin_class_member_offsets_to_roc_source_str(decoded))?
    Path.join(roc_out_path, "engine/NativeStructures.roc").write_utf8!(native_structures_to_roc_source_str(decoded))?
    Path.join(roc_out_path, "engine/UtilityFunctions.roc").write_utf8!(utility_functions_to_roc_source_str(decoded))?

    for bic in decoded.builtin_classes {
        mod_name = builtin_module_name(bic.name)
        Path.join(roc_out_path, "engine/builtin_classes/${mod_name}.roc")
            .write_utf8!(builtin_class_to_roc_source_str(bic))?
    }

    for cls in decoded.classes {
        mod_name = class_module_name(cls.name)
        Path.join(roc_out_path, "engine/classes/${mod_name}.roc")
            .write_utf8!(class_to_roc_source_str(cls))?
    }

    for s in decoded.singletons {
        mod_name = singleton_module_name(s.name)
        Path.join(roc_out_path, "engine/singletons/${mod_name}.roc")
            .write_utf8!(singleton_to_roc_source_str(s))?
    }

    Path.join(roc_out_path, "main.roc").write_utf8!(gen_package_main_roc(decoded))?

    Path.join("src", "zig_platform_abi_impl.zig")
        .write_utf8!(zig_platform_abi_impl_to_str(decoded))?

    Stdout.line!("# done total ${(Utc.now!() - parse_start).to_str()}ns")?
    Ok({})
}

# --- naming ---------------------------------------------------------------

builtin_module_name : Str -> Str
builtin_module_name = |name| {
    match name {
        "bool" => "GodotBool"
        "int" => "GodotInt"
        "float" => "GodotFloat"
        other => other
    }
}

class_module_name : Str -> Str
class_module_name = |name| {
    match name {
        "Crypto" => "GodotCrypto"
        "Range" => "GodotRange"
        other => other
    }
}

singleton_module_name : Str -> Str
singleton_module_name = |name| "${name}Singleton"

roc_type_ident : Str -> Str
roc_type_ident = |s|
    s.replace_each("::", "_").replace_each(".", "_").replace_each(" ", "_").replace_each("/", "_")

## Value names must start lowercase in Roc (uppercase = type)
to_value_name : Str -> Str
to_value_name = |s| s.with_ascii_lowercased()

c_to_roc_type : Str -> Str
c_to_roc_type = |str| {
    match str {
        "int" => "I32"
        "float" => "F32"
        "double" => "F64"
        "bool" => "Bool"
        "void" => "{}"
        "Crypto" => "GodotCrypto"
        "Range" => "GodotRange"
        other => builtin_module_name(other)
    }
}

# --- package root ---------------------------------------------------------

gen_package_main_roc : ExtensionApi -> Str
gen_package_main_roc = |eapi| {

    builtin_names = eapi.builtin_classes.map(|b| builtin_module_name(b.name))
    class_names = eapi.classes.map(|c| class_module_name(c.name))
    singleton_names = eapi.singletons.map(|s| singleton_module_name(s.name))

    meta_names = [
        "Host",
        "GlobalConstants",
        "GlobalEnums",
        "BuiltinClassSizes",
        "BuiltinClassMemberOffsets",
        "NativeStructures",
        "UtilityFunctions",
    ]

    all_names =
        List.concat(meta_names, List.concat(builtin_names, List.concat(class_names, singleton_names)))

    expose = Str.join_with(all_names.map(|n| "    ${n}"), ",\n")

    meta_imports =
        \\import Host as Host
        \\import engine/GlobalConstants as GlobalConstants
        \\import engine/GlobalEnums as GlobalEnums
        \\import engine/BuiltinClassSizes as BuiltinClassSizes
        \\import engine/BuiltinClassMemberOffsets as BuiltinClassMemberOffsets
        \\import engine/NativeStructures as NativeStructures
        \\import engine/UtilityFunctions as UtilityFunctions

    builtin_imports =
        Str.join_with(builtin_names.map(|n| "import engine/builtin_classes/${n} as ${n}"), "\n")

    class_imports =
        Str.join_with(class_names.map(|n| "import engine/classes/${n} as ${n}"), "\n")

    singleton_imports =
        Str.join_with(singleton_names.map(|n| "import engine/singletons/${n} as ${n}"), "\n")

    \\# AUTO-GENERATED — do not edit
    \\package [
    \\${expose}
    \\] {}
    \\
    \\${meta_imports}
    \\
    \\${builtin_imports}
    \\
    \\${class_imports}
    \\
    \\${singleton_imports}
    \\
}

render_header : ExtensionApi -> Str
render_header = |eapi|
    \\# ${eapi.header.version_full_name}
    \\# builtins=${eapi.builtin_classes.len().to_str()} classes=${eapi.classes.len().to_str()} singletons=${eapi.singletons.len().to_str()}

# --- Host -----------------------------------------------------------------

host_to_roc_source_str : ExtensionApi -> Str
host_to_roc_source_str = |eapi| {
    util_stubs =
        Str.join_with(
            eapi.utility_functions.map(|uf|
                \\    # util_${uf.name}_${uf.hash.to_str()}!
            ),
            "\n",
        )
    sing_stubs =
        Str.join_with(
            eapi.singletons.map(|s| "    # get_singleton_${s.name}!"),
            "\n",
        )
    \\# AUTO-GENERATED Host surface
    \\Host := {
    \\}.{
    \\${sing_stubs}
    \\${util_stubs}
    \\}
}

# --- GlobalConstants: nominal module + lowercase values -------------------

global_constants_to_roc_source_str : ExtensionApi -> Str
global_constants_to_roc_source_str = |eapi| {
    body =
        Str.join_with(
            eapi.global_constants.map(|gc| {
                vn = to_value_name(gc.name)
                \\    ${vn} : I64
                \\    ${vn} = ${gc.value.to_str()}
            }),
            "\n",
        )
    \\# AUTO-GENERATED global_constants
    \\GlobalConstants := {
    \\}.{
    \\${body}
    \\}
}

# --- GlobalEnums: nominal module + associated tag unions ------------------

global_enums_to_roc_source_str : ExtensionApi -> Str
global_enums_to_roc_source_str = |eapi| {
    body =
        Str.join_with(
            eapi.global_enums.map(|e| {
                ename = roc_type_ident(e.name)
                values = Str.join_with(e.values.map(|v| v.name), ", ")
                notes =
                    Str.join_with(
                        e.values.map(|v| "    # ${ename}_${v.name} = ${v.value.to_str()}"),
                        "\n",
                    )
                \\    ${ename} : [${values}]
                \\${notes}
            }),
            "\n",
        )
    \\# AUTO-GENERATED global_enums
    \\GlobalEnums := {
    \\}.{
    \\${body}
    \\}
}

# --- sizes / offsets / native / utility: nominal + comments only ----------

builtin_class_sizes_to_roc_source_str : ExtensionApi -> Str
builtin_class_sizes_to_roc_source_str = |eapi| {
    body =
        Str.join_with(
            eapi.builtin_class_sizes.map(|bcs| {
                lines =
                    Str.join_with(
                        bcs.sizes.map(|ns| "    # ${ns.name} = ${ns.size.to_str()}"),
                        "\n",
                    )
                \\    # build_configuration: ${bcs.build_configuration}
                \\${lines}
            }),
            "\n",
        )
    \\# AUTO-GENERATED builtin_class_sizes
    \\BuiltinClassSizes := {
    \\}.{
    \\${body}
    \\}
}

builtin_class_member_offsets_to_roc_source_str : ExtensionApi -> Str
builtin_class_member_offsets_to_roc_source_str = |eapi| {
    body =
        Str.join_with(
            eapi.builtin_class_member_offsets.map(|bco| {
                classes =
                    Str.join_with(
                        bco.classes.map(|bc| {
                            ms =
                                Str.join_with(
                                    bc.members.map(|m| "    #   ${m.member} @ ${m.offset.to_str()}"),
                                    "\n",
                                )
                            \\    # class ${bc.name}
                            \\${ms}
                        }),
                        "\n",
                    )
                \\    # build_configuration: ${bco.build_configuration}
                \\${classes}
            }),
            "\n",
        )
    \\# AUTO-GENERATED builtin_class_member_offsets
    \\BuiltinClassMemberOffsets := {
    \\}.{
    \\${body}
    \\}
}

native_structures_to_roc_source_str : ExtensionApi -> Str
native_structures_to_roc_source_str = |eapi| {
    body =
        Str.join_with(
            eapi.native_structures.map(|ns| "    # ${ns.name}: ${ns.format}"),
            "\n",
        )
    \\# AUTO-GENERATED native_structures
    \\NativeStructures := {
    \\}.{
    \\${body}
    \\}
}

utility_functions_to_roc_source_str : ExtensionApi -> Str
utility_functions_to_roc_source_str = |eapi| {
    body =
        Str.join_with(
            eapi.utility_functions.map(|uf| {
                ret =
                    match uf.return_type {
                        Ok(rt) => c_to_roc_type(rt)
                        _ => "{}"
                    }
                args =
                    match uf.arguments {
                        Ok(a) if !(a.is_empty()) => Str.join_with(a.map(|x| c_to_roc_type(x.type)), ", ")
                        _ => "{}"
                    }
                \\    # ${uf.name}! : ${args} -> ${ret}  # hash ${uf.hash.to_str()}
            }),
            "\n",
        )
    \\# AUTO-GENERATED utility_functions
    \\UtilityFunctions := {
    \\}.{
    \\${body}
    \\}
}

# --- method helpers -------------------------------------------------------

method_arg_types : MethodDef -> Str
method_arg_types = |md|
    match md.arguments {
        Ok(args) if !(args.is_empty()) => Str.join_with(args.map(|a| c_to_roc_type(a.type)), ", ")
        _ => "()"
    }

method_return_type : MethodDef -> Str
method_return_type = |md|
    match md.return_type {
        Ok(rt) => c_to_roc_type(rt)
        _ =>
            match md.return_value {
                Ok(rv) => c_to_roc_type(rv.type)
                _ => "{}"
            }
    }

method_def_line : MethodDef -> Str
method_def_line = |md|
    \\    # ${md.name}! : ${method_arg_types(md)} -> ${method_return_type(md)}
    \\    # ${md.name}! = Host.${md.name}_${md.hash.to_str()}!

property_def_line : PropertyDef -> Str
property_def_line = |p|
    \\    # property ${p.name} : ${c_to_roc_type(p.type)}

signal_def_line : SignalDef -> Str
signal_def_line = |sig| {
    args =
        match sig.arguments {
            Ok(a) if !(a.is_empty()) => Str.join_with(a.map(|x| "${x.name} : ${c_to_roc_type(x.type)}"), ", ")
            _ => "()"
        }
    \\    # signal ${sig.name} : ${args}
}

enum_def_line : EnumDef -> Str
enum_def_line = |e| {
    ename = roc_type_ident(e.name)
    values = Str.join_with(e.values.map(|v| v.name), ", ")
    \\    ${ename} : [${values}]
}

methods_block = |maybe| match maybe { Ok(ms) => Str.join_with(ms.map(method_def_line), "\n") _ => "" }
properties_block = |maybe| match maybe { Ok(ps) => Str.join_with(ps.map(property_def_line), "\n") _ => "" }
signals_block = |maybe| match maybe { Ok(ss) => Str.join_with(ss.map(signal_def_line), "\n") _ => "" }
enums_block = |maybe| match maybe { Ok(es) => Str.join_with(es.map(enum_def_line), "\n") _ => "" }

# --- builtins (sibling imports: bare module name, same directory) ---------

builtin_class_to_roc_source_str : BuiltinClass -> Str
builtin_class_to_roc_source_str = |bic| {

    type_name = builtin_module_name(bic.name)

    members_list =
        match bic.members {
            Ok(ms) => ms
            _ => []
        }

    has_members = !(members_list.is_empty())

    unique =
        members_list.map(|m| c_to_roc_type(m.type)).fold(
            [],
            |acc, t| {
                is_prim =
                    match t {
                        "I32" | "F32" | "F64" | "Bool" | "{}" | "U64" => Bool.True
                        _ => Bool.False
                    }
                if is_prim {
                    acc
                } else {
                    if t == type_name {
                        acc
                    } else {
                        if List.contains(acc, t) {
                            acc
                        } else {
                            List.append(acc, t)
                        }
                    }
                }
            },
        )

    # SAME directory as this module → do NOT prefix engine/builtin_classes/
    import_lines =
        Str.join_with(unique.map(|t| "import ${t} as ${t}"), "\n")

    members_str =
        if has_members {
            Str.join_with(members_list.map(|m| "    ${m.name} : ${c_to_roc_type(m.type)}"), ",\n")
        } else {
            "    ptr : U64"
        }

    construct_sig =
        if has_members {
            arg_tys = Str.join_with(members_list.map(|m| c_to_roc_type(m.type)), ", ")
            arg_ns = Str.join_with(members_list.map(|m| m.name), ", ")
            \\    construct_default! : ${arg_tys} -> ${type_name}
            \\    construct_default! = |${arg_ns}| { { ${arg_ns} } }
        } else {
            \\    construct_default! : {} -> ${type_name}
            \\    construct_default! = |_| { { ptr: 0 } }
        }

    constructors_str =
        Str.join_with(
            bic.constructors
                .keep_if(|c| c.arguments != Err(Missing))
                .map(|c| {
                    arg_types =
                        match c.arguments {
                            Ok(args) => Str.join_with(args.map(|a| c_to_roc_type(a.type)), ", ")
                            _ => ""
                        }
                    \\    # construct_${c.index.to_str()}! : ${arg_types} -> ${type_name}
                }),
            "\n",
        )

    constants_str =
        match bic.constants {
            Ok(cs) =>
                Str.join_with(
                    cs.map(|c| {
                        vn = to_value_name(c.name)
                        vs =
                            c.value
                                .replace_first(bic.name, "construct_default!")
                                .replace_each("inf", "F32.infinity")
                        \\    # ${vn} = ${vs}
                    }),
                    "\n",
                )
            _ => ""
        }

    operators_str =
        Str.join_with(
            bic.operators.map(|op| "    # op ${op.name}"),
            "\n",
        )

    imports_section =
        if import_lines == "" {
            ""
        } else {
            "${import_lines}\n\n"
        }

    \\# builtin ${bic.name} → ${type_name}
    \\${imports_section}${type_name} := {
    \\${members_str}
    \\}.{
    \\${construct_sig}
    \\${constructors_str}
    \\${constants_str}
    \\${enums_block(bic.enums)}
    \\${methods_block(bic.methods)}
    \\${operators_str}
    \\}
}

# --- classes / singletons -------------------------------------------------

class_to_roc_source_str : ClassDef -> Str
class_to_roc_source_str = |cls| {
    type_name = class_module_name(cls.name)
    inherits_line =
        match cls.inherits {
            Ok(p) => "# inherits: ${p}\n"
            _ => ""
        }
    \\# class ${cls.name} → ${type_name}
    \\${inherits_line}${type_name} := {
    \\    ptr : U64,
    \\}.{
    \\${enums_block(cls.enums)}
    \\${properties_block(cls.properties)}
    \\${methods_block(cls.methods)}
    \\${signals_block(cls.signals)}
    \\}
}

singleton_to_roc_source_str : Singleton -> Str
singleton_to_roc_source_str = |st| {
    mod_name = singleton_module_name(st.name)
    \\# singleton ${st.name} → ${mod_name}
    \\${mod_name} := {
    \\    ptr : U64,
    \\}.{
    \\}
}

# --- Zig ABI stubs --------------------------------------------------------

zig_platform_abi_impl_to_str : ExtensionApi -> Str
zig_platform_abi_impl_to_str = |eapi| {
    utils =
        Str.join_with(
            eapi.utility_functions.map(|uf|
                \\
                \\export fn godot_roc_util_${uf.name}_${uf.hash.to_str()}() callconv(.c) void {
                \\    // TODO: GDExtension utility ${uf.name}
                \\}
            ),
            "\n",
        )
    sings =
        Str.join_with(
            eapi.singletons.map(|s|
                \\
                \\export fn godot_roc_get_singleton_${s.name}() callconv(.c) u64 {
                \\    return 0; // TODO: ${s.name}
                \\}
            ),
            "\n",
        )
    \\//! AUTO-GENERATED C-ABI for Roc Host / roc glue
    \\const std = @import("std");
    \\${sings}
    \\${utils}
    \\
}
