#!/usr/bin/env roc

#
# Usage:
#   roc run scripts/glue.roc -- wasm32
#   roc run scripts/glue.roc -- native64
#

## Continous Intergration
app [main!] {
    roc: "nightly-2026-09-18-1d982dc",
    pf: platform "https://github.com/roc-lang/basic-cli/releases/download/0.22.2/9zUBxb1LtXYVc4eR4hAtd1WQDwBYDhM6HQdZz1UFCm2m.tar.zst"
}

import pf.OsStr
import pf.Path
import pf.Stdout
import pf.Stdin
import pf.Utc
import pf.Cmd
import pf.Env

#main! : List(OsStr) => Try({}, _)
main! = |args| {

    Stdout.line!("args: ${Str.inspect(args)}")?
    Stdout.line!("display: ${args.last()?.display()}")?

    target : [DesktopNative64, WebWasm32] # Godot target...
    target = match (args.last()?.display()) {
        "wasm32" => WebWasm32,
        "native64" => DesktopNative64
        _ => crash "[scripts/glue.roc] Missing args, pass either as the last arg: [wasm32|native64]"
    }
    Stdout.line!("target: ${Str.inspect(target)}")?

   	Path.write_utf8!("platform/Size.roc",
        \\## IMPORTANT: This file is generated by scripts/glue.roc
        \\## IMPORTANT: This file is generated by scripts/glue.roc
        \\Size := [].{
        \\
        \\    ## Pointer-sized unsigned integer for the current target.
        \\    ## Swap this file (or regenerate it) for wasm32 vs native.
        \\    ## IMPORTANT: USIZE is generated by scripts/glue.roc
        \\    USIZE : ${match (target) {
            DesktopNative64 => "U64",
            WebWasm32 => "U32"
        }}
        \\
        \\    ## Godot object handle / pointer-sized value across the Roc ↔ host boundary.
        \\    GDExtensionObjectPtr : USIZE
        \\}
	)?

    _glue_out = Cmd.exec!("roc", ["glue", "vendor/roc/ZigGlue.roc", "src/", "platform/main.roc"])?

    # Patch glue..

    generated_glue = Path.read_utf8!("src/roc_platform_abi.zig")?

    s1 = find_and_replace_first(
        generated_glue,
        # --- find (unpatched, as emitted by roc glue) ---
        \\    fn nativeWriteStderr(_: ?*anyopaque, data: []const u8) void {
        \\        std.Io.File.stderr().writeStreamingAll(std.Io.Threaded.global_single_threaded.io(), data) catch {};
        \\    }
        ,
        # --- replace ---
        \\// PATCHED BY scripts/glue.roc
        \\fn nativeWriteStderr(_: ?*anyopaque, data: []const u8) void {
        \\    _ = data;
        \\}
        ,
    )
    s2 = find_and_replace_first(
        s1,
        \\    fn nativeOnFatal(_: ?*anyopaque) noreturn {
        \\        std.process.exit(1);
        \\    }
        ,
        \\// PATCHED BY scripts/glue.roc
        \\fn nativeOnFatal(_: ?*anyopaque) noreturn {
        \\    @trap();
        \\}
        ,
    )



    Path.write_utf8!("src/roc_platform_abi.zig", s2)?

    Ok({})
}

## Exact match only. Crashes if `find_str` is missing so CI fails when glue output changes.
find_and_replace_first : Str, Str, Str -> Str
find_and_replace_first = |body_str, find_str, replacement_str| {
    if body_str.contains(find_str) {
        body_str.replace_first(find_str, replacement_str)
    } else {
        crash "[scripts/glue.roc] pattern not found in src/roc_platform_abi.zig:\n${find_str}"
    }
}
