import Godot

GodotToRocMapper := {}.{
    to_str : Godot.ExtensionApi -> Str
    to_str = |gd_api| {
        \\###
        \\### ${gd_api.header.version_full_name}
        \\### ${gd_api.header.version_build}
        \\### ${gd_api.header.version_status}
        \\### ${gd_api.header.precision}
        \\### ${gd_api.header.version_major.to_str()}.${gd_api.header.version_minor.to_str()}.${gd_api.header.version_patch.to_str()}
        \\###
        \\### Generated By GodotToRocMapper
        \\###
        \\
        \\## ${gd_api.header.version_full_name}
        \\GeneratedGodotExtensionApi := {}.{
        \\
        \\  # global_constants:
        \\  ${constants_to_str(gd_api.global_constants)}
        \\
        \\  # etc.
        \\}
    }

    constants_to_str : List(Godot.GlobalConstant) -> Str
    constants_to_str = |gcs| {
        strs : List(Str)
        strs = gcs.map(|gc| "${gc.name} = ${gc.value.to_str()}\n")

        str : Str
        str = strs.fold("", |a, b| "${a} ${b}")

        str
    }
}
