import Godot

GodotToZigMapper := {}.{
    to_str : Godot.ExtensionApi -> Str
    to_str = |gd_api| {
        \\///
        \\/// ${gd_api.header.version_full_name}
        \\/// ${gd_api.header.version_build}
        \\/// ${gd_api.header.version_status}
        \\/// ${gd_api.header.precision}
        \\/// ${gd_api.header.version_major.to_str()}.${gd_api.header.version_minor.to_str()}.${gd_api.header.version_patch.to_str()}
        \\///
        \\/// Generated By GodotToZigMapper
        \\///
        \\
        \\// builtin_class_sizes
        \\${builtin_class_sizes_to_str(gd_api.builtin_class_sizes)}
        \\
        \\// builtin_class_member_offsets
        \\${builtin_class_member_offsets_sizes_to_str(gd_api.builtin_class_member_offsets)}
        \\
        \\// global_constants
        \\${global_constants_to_str(gd_api.global_constants)}
        \\
        \\// global_enums
        \\${global_enums_to_str(gd_api.global_enums)}
        \\
        \\// utility_functions
        \\${utility_functions_to_str(gd_api.utility_functions)}
        \\
        \\// builtin_classes
        \\${builtin_classes_to_str(gd_api.builtin_classes)}
        \\
        \\// classes
        \\${classes_to_str(gd_api.classes)}
        \\
        \\// singletons
        \\${singletons_to_str(gd_api.singletons)}
        \\
        \\// native_structures
        \\${native_structures_to_str(gd_api.native_structures)}
        \\
    }

    builtin_class_sizes_to_str : List(Godot.BuiltinClassSizes) -> Str
    builtin_class_sizes_to_str = |bicss| {
        strs : List(Str)
        strs = bicss.map(|bcs| "${bcs.sizes.map(|x| "const BUILTIN_CLASS_SIZE_${bcs.build_configuration}_${x.name} = ${x.size.to_str()};").fold("", |a, b| "${a}\n${b}")}\n")

        str : Str
        str = strs.fold("", |a, b| "${a} ${b}")

        str
    }

    builtin_class_member_offsets_sizes_to_str : List(Godot.BuiltinClassMemberOffsets) -> Str
    builtin_class_member_offsets_sizes_to_str = |bcmos| {
        strs : List(Str)
        strs =
            bcmos.join_map(|bcmo|
                bcmo.classes.join_map(|bmc|
                    bmc.members.map(|mo|
                        "const BUILTIN_CLASS_SIZE_OFFSET_${bcmo.build_configuration}_${bmc.name}_${mo.member} = ${mo.offset.to_str()};\n"
                    )
                )
            )

        str : Str
        str = strs.fold("", |a, b| "${a} ${b}")

        str
    }

    global_constants_to_str : List(Godot.GlobalConstant) -> Str
    global_constants_to_str = |gcs| {
        strs : List(Str)
        strs = gcs.map(|gc| "const GLOBAL_CONSTANT_${gc.name} = ${gc.value.to_str()};\n")

        str : Str
        str = strs.fold("", |a, b| "${a} ${b}")

        str
    }

    global_enums_to_str : List(Godot.EnumDef) -> Str
    global_enums_to_str = |eds| {
        strs : List(Str)
        strs = eds.map(|ed| "const ENUM_DEF_${ed.name.replace_each(".","_")} = \"${ed.name}\";\n")

        str : Str
        str = strs.fold("", |a, b| "${a} ${b}")

        str
    }

    utility_functions_to_str : List(Godot.UtilityFunction) -> Str
    utility_functions_to_str = |ufs| {
        strs : List(Str)
        strs = ufs.map(|uf| "const UTILITY_FUNCTION_${uf.name}_HASH = ${uf.hash.to_str()}; // ${uf.category}\n")

        str : Str
        str = strs.fold("", |a, b| "${a} ${b}")

        str
    }

    builtin_classes_to_str : List(Godot.BuiltinClass) -> Str
    builtin_classes_to_str = |bics| {
        strs : List(Str)
            strs = bics.map(|bic| "const BUILTIN_CLASS_${bic.name} = \"${bic.name}\"; ${
            match bic.methods {
                Ok(_) => "// Methods",
                _ => "// Missing Methods."
            }
        } \n")

        str : Str
        str = strs.fold("", |a, b| "${a} ${b}")

        str
    }

    classes_to_str : List(Godot.ClassDef) -> Str
    classes_to_str = |cds| {
        strs : List(Str)
        strs = cds.map(|cd| "const CLASS_DEF_${cd.name} = \"${cd.api_type}\";${
        match cd.methods {
            Ok(_) => "// Methods",
            _ => "// Missing Methods."
        }
    }\n")

        str : Str
        str = strs.fold("", |a, b| "${a} ${b}")

        str
    }

    singletons_to_str : List(Godot.Singleton) -> Str
    singletons_to_str = |sts| {
        strs : List(Str)
        strs = sts.map(|st| "const SINGLETON_${st.name} = \"${st.type}\";\n")

        str : Str
        str = strs.fold("", |a, b| "${a} ${b}")

        str
    }

    native_structures_to_str : List(Godot.NativeStructure) -> Str
    native_structures_to_str = |nss| {
        strs : List(Str)
        strs = nss.map(|ns| "const NATIVE_STRUCTURE_${ns.name} = \"${ns.format}\";\n")

        str : Str
        str = strs.fold("", |a, b| "${a} ${b}")

        str
    }
}
