###
### Godot Engine v4.7.2.stable.nixpkgs
### nixpkgs
### stable
### single
### 4.7.2
###
### Generated By GodotToRocMapper
###

## Godot Engine v4.7.2.stable.nixpkgs
GeneratedGodotExtensionApi := {}.{

    # global_constants:
    UINT8_MAX = 255
    UINT16_MAX = 65535
    UINT32_MAX = 4294967295
    INT8_MIN = -128
    INT8_MAX = 127
    INT16_MIN = -32768
    INT16_MAX = 32767
    INT32_MIN = -2147483648
    INT32_MAX = 2147483647
    INT64_MIN = -9223372036854775808
    INT64_MAX = 9223372036854775807


  # etc.
}
