//! AUTO-GENERATED by scripts/extension_api.generate.roc — do not edit by hand
//! C-ABI surface for the Roc Godot host (roc glue ↔ Zig ↔ GDExtension).
//!
//! Naming convention:
//!   Host.util_<name>_<hash>!     →  export fn godot_roc_util_<name>_<hash>
//!   Host.get_singleton_<Name>! →  export fn godot_roc_get_singleton_<Name>
//!   Host.<method>_<hash>!      →  export fn godot_roc_<method>_<hash>  (add per bind)
//!
//! After `roc glue`, align symbol names with the generated host header if they differ.

const std = @import("std");
// const abi = @import("roc_std");           // RocStr, etc. — wire to your glue output
// const gde = @import("gdextension_interface");
// const baseline_gde_if = gde;

// ---------------------------------------------------------------------------
// Helpers (fill in from your existing native_host.zig)
// ---------------------------------------------------------------------------

// var g_roc_host: ?*abi.RocHost = null;
// fn getMethodBind(class_name: []const u8, method: []const u8, hash: u64) gde.GDExtensionMethodBindPtr { ... }
// fn ptrcall(mb: gde.GDExtensionMethodBindPtr, obj: gde.GDExtensionObjectPtr, args: ?[*]const gde.GDExtensionConstTypePtr, ret: gde.GDExtensionTypePtr) void { ... }

/// Example: borrow RocStr → temporary null-terminated slice (stack if short).
fn rocStrToZ(action: anytype, buf: []u8) ?[:0]const u8 {
    // var owned = action;
    // defer owned.decref(g_roc_host.?);
    // const s = owned.asSlice();
    // if (s.len >= buf.len) return null;
    // @memcpy(buf[0..s.len], s);
    // buf[s.len] = 0;
    // return buf[0..s.len :0];
    _ = action;
    _ = buf;
    return null;
}

// ---------------------------------------------------------------------------
// Singletons
// ---------------------------------------------------------------------------

/// Singleton Performance (type Performance)
/// Roc: Host.get_singleton_Performance! / get_singleton_ptr!("Performance")
export fn godot_roc_get_singleton_Performance() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("Performance"))
    return 0;
}

/// Singleton Engine (type Engine)
/// Roc: Host.get_singleton_Engine! / get_singleton_ptr!("Engine")
export fn godot_roc_get_singleton_Engine() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("Engine"))
    return 0;
}

/// Singleton ProjectSettings (type ProjectSettings)
/// Roc: Host.get_singleton_ProjectSettings! / get_singleton_ptr!("ProjectSettings")
export fn godot_roc_get_singleton_ProjectSettings() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("ProjectSettings"))
    return 0;
}

/// Singleton OS (type OS)
/// Roc: Host.get_singleton_OS! / get_singleton_ptr!("OS")
export fn godot_roc_get_singleton_OS() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("OS"))
    return 0;
}

/// Singleton Time (type Time)
/// Roc: Host.get_singleton_Time! / get_singleton_ptr!("Time")
export fn godot_roc_get_singleton_Time() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("Time"))
    return 0;
}

/// Singleton ClassDB (type ClassDB)
/// Roc: Host.get_singleton_ClassDB! / get_singleton_ptr!("ClassDB")
export fn godot_roc_get_singleton_ClassDB() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("ClassDB"))
    return 0;
}

/// Singleton TextServerManager (type TextServerManager)
/// Roc: Host.get_singleton_TextServerManager! / get_singleton_ptr!("TextServerManager")
export fn godot_roc_get_singleton_TextServerManager() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("TextServerManager"))
    return 0;
}

/// Singleton NavigationServer2DManager (type NavigationServer2DManager)
/// Roc: Host.get_singleton_NavigationServer2DManager! / get_singleton_ptr!("NavigationServer2DManager")
export fn godot_roc_get_singleton_NavigationServer2DManager() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("NavigationServer2DManager"))
    return 0;
}

/// Singleton PhysicsServer2DManager (type PhysicsServer2DManager)
/// Roc: Host.get_singleton_PhysicsServer2DManager! / get_singleton_ptr!("PhysicsServer2DManager")
export fn godot_roc_get_singleton_PhysicsServer2DManager() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("PhysicsServer2DManager"))
    return 0;
}

/// Singleton NavigationServer3DManager (type NavigationServer3DManager)
/// Roc: Host.get_singleton_NavigationServer3DManager! / get_singleton_ptr!("NavigationServer3DManager")
export fn godot_roc_get_singleton_NavigationServer3DManager() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("NavigationServer3DManager"))
    return 0;
}

/// Singleton PhysicsServer3DManager (type PhysicsServer3DManager)
/// Roc: Host.get_singleton_PhysicsServer3DManager! / get_singleton_ptr!("PhysicsServer3DManager")
export fn godot_roc_get_singleton_PhysicsServer3DManager() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("PhysicsServer3DManager"))
    return 0;
}

/// Singleton NavigationMeshGenerator (type NavigationMeshGenerator)
/// Roc: Host.get_singleton_NavigationMeshGenerator! / get_singleton_ptr!("NavigationMeshGenerator")
export fn godot_roc_get_singleton_NavigationMeshGenerator() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("NavigationMeshGenerator"))
    return 0;
}

/// Singleton IP (type IP)
/// Roc: Host.get_singleton_IP! / get_singleton_ptr!("IP")
export fn godot_roc_get_singleton_IP() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("IP"))
    return 0;
}

/// Singleton Geometry2D (type Geometry2D)
/// Roc: Host.get_singleton_Geometry2D! / get_singleton_ptr!("Geometry2D")
export fn godot_roc_get_singleton_Geometry2D() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("Geometry2D"))
    return 0;
}

/// Singleton Geometry3D (type Geometry3D)
/// Roc: Host.get_singleton_Geometry3D! / get_singleton_ptr!("Geometry3D")
export fn godot_roc_get_singleton_Geometry3D() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("Geometry3D"))
    return 0;
}

/// Singleton ResourceLoader (type ResourceLoader)
/// Roc: Host.get_singleton_ResourceLoader! / get_singleton_ptr!("ResourceLoader")
export fn godot_roc_get_singleton_ResourceLoader() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("ResourceLoader"))
    return 0;
}

/// Singleton ResourceSaver (type ResourceSaver)
/// Roc: Host.get_singleton_ResourceSaver! / get_singleton_ptr!("ResourceSaver")
export fn godot_roc_get_singleton_ResourceSaver() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("ResourceSaver"))
    return 0;
}

/// Singleton Marshalls (type Marshalls)
/// Roc: Host.get_singleton_Marshalls! / get_singleton_ptr!("Marshalls")
export fn godot_roc_get_singleton_Marshalls() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("Marshalls"))
    return 0;
}

/// Singleton TranslationServer (type TranslationServer)
/// Roc: Host.get_singleton_TranslationServer! / get_singleton_ptr!("TranslationServer")
export fn godot_roc_get_singleton_TranslationServer() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("TranslationServer"))
    return 0;
}

/// Singleton Input (type Input)
/// Roc: Host.get_singleton_Input! / get_singleton_ptr!("Input")
export fn godot_roc_get_singleton_Input() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("Input"))
    return 0;
}

/// Singleton InputMap (type InputMap)
/// Roc: Host.get_singleton_InputMap! / get_singleton_ptr!("InputMap")
export fn godot_roc_get_singleton_InputMap() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("InputMap"))
    return 0;
}

/// Singleton EngineDebugger (type EngineDebugger)
/// Roc: Host.get_singleton_EngineDebugger! / get_singleton_ptr!("EngineDebugger")
export fn godot_roc_get_singleton_EngineDebugger() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("EngineDebugger"))
    return 0;
}

/// Singleton GDExtensionManager (type GDExtensionManager)
/// Roc: Host.get_singleton_GDExtensionManager! / get_singleton_ptr!("GDExtensionManager")
export fn godot_roc_get_singleton_GDExtensionManager() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("GDExtensionManager"))
    return 0;
}

/// Singleton ResourceUID (type ResourceUID)
/// Roc: Host.get_singleton_ResourceUID! / get_singleton_ptr!("ResourceUID")
export fn godot_roc_get_singleton_ResourceUID() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("ResourceUID"))
    return 0;
}

/// Singleton WorkerThreadPool (type WorkerThreadPool)
/// Roc: Host.get_singleton_WorkerThreadPool! / get_singleton_ptr!("WorkerThreadPool")
export fn godot_roc_get_singleton_WorkerThreadPool() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("WorkerThreadPool"))
    return 0;
}

/// Singleton ThemeDB (type ThemeDB)
/// Roc: Host.get_singleton_ThemeDB! / get_singleton_ptr!("ThemeDB")
export fn godot_roc_get_singleton_ThemeDB() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("ThemeDB"))
    return 0;
}

/// Singleton EditorInterface (type EditorInterface)
/// Roc: Host.get_singleton_EditorInterface! / get_singleton_ptr!("EditorInterface")
export fn godot_roc_get_singleton_EditorInterface() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("EditorInterface"))
    return 0;
}

/// Singleton GDScriptLanguageProtocol (type GDScriptLanguageProtocol)
/// Roc: Host.get_singleton_GDScriptLanguageProtocol! / get_singleton_ptr!("GDScriptLanguageProtocol")
export fn godot_roc_get_singleton_GDScriptLanguageProtocol() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("GDScriptLanguageProtocol"))
    return 0;
}

/// Singleton JavaClassWrapper (type JavaClassWrapper)
/// Roc: Host.get_singleton_JavaClassWrapper! / get_singleton_ptr!("JavaClassWrapper")
export fn godot_roc_get_singleton_JavaClassWrapper() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("JavaClassWrapper"))
    return 0;
}

/// Singleton JavaScriptBridge (type JavaScriptBridge)
/// Roc: Host.get_singleton_JavaScriptBridge! / get_singleton_ptr!("JavaScriptBridge")
export fn godot_roc_get_singleton_JavaScriptBridge() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("JavaScriptBridge"))
    return 0;
}

/// Singleton AccessibilityServer (type AccessibilityServer)
/// Roc: Host.get_singleton_AccessibilityServer! / get_singleton_ptr!("AccessibilityServer")
export fn godot_roc_get_singleton_AccessibilityServer() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("AccessibilityServer"))
    return 0;
}

/// Singleton AudioServer (type AudioServer)
/// Roc: Host.get_singleton_AudioServer! / get_singleton_ptr!("AudioServer")
export fn godot_roc_get_singleton_AudioServer() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("AudioServer"))
    return 0;
}

/// Singleton CameraServer (type CameraServer)
/// Roc: Host.get_singleton_CameraServer! / get_singleton_ptr!("CameraServer")
export fn godot_roc_get_singleton_CameraServer() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("CameraServer"))
    return 0;
}

/// Singleton DisplayServer (type DisplayServer)
/// Roc: Host.get_singleton_DisplayServer! / get_singleton_ptr!("DisplayServer")
export fn godot_roc_get_singleton_DisplayServer() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("DisplayServer"))
    return 0;
}

/// Singleton NativeMenu (type NativeMenu)
/// Roc: Host.get_singleton_NativeMenu! / get_singleton_ptr!("NativeMenu")
export fn godot_roc_get_singleton_NativeMenu() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("NativeMenu"))
    return 0;
}

/// Singleton RenderingServer (type RenderingServer)
/// Roc: Host.get_singleton_RenderingServer! / get_singleton_ptr!("RenderingServer")
export fn godot_roc_get_singleton_RenderingServer() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("RenderingServer"))
    return 0;
}

/// Singleton NavigationServer2D (type NavigationServer2D)
/// Roc: Host.get_singleton_NavigationServer2D! / get_singleton_ptr!("NavigationServer2D")
export fn godot_roc_get_singleton_NavigationServer2D() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("NavigationServer2D"))
    return 0;
}

/// Singleton NavigationServer3D (type NavigationServer3D)
/// Roc: Host.get_singleton_NavigationServer3D! / get_singleton_ptr!("NavigationServer3D")
export fn godot_roc_get_singleton_NavigationServer3D() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("NavigationServer3D"))
    return 0;
}

/// Singleton PhysicsServer2D (type PhysicsServer2D)
/// Roc: Host.get_singleton_PhysicsServer2D! / get_singleton_ptr!("PhysicsServer2D")
export fn godot_roc_get_singleton_PhysicsServer2D() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("PhysicsServer2D"))
    return 0;
}

/// Singleton PhysicsServer3D (type PhysicsServer3D)
/// Roc: Host.get_singleton_PhysicsServer3D! / get_singleton_ptr!("PhysicsServer3D")
export fn godot_roc_get_singleton_PhysicsServer3D() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("PhysicsServer3D"))
    return 0;
}

/// Singleton XRServer (type XRServer)
/// Roc: Host.get_singleton_XRServer! / get_singleton_ptr!("XRServer")
export fn godot_roc_get_singleton_XRServer() callconv(.c) u64 {
    // TODO: gdextension interface get_singleton(StringName("XRServer"))
    return 0;
}

export fn godot_roc_get_singleton_ptr(name_ptr: [*]const u8, name_len: usize) callconv(.c) u64 {
    _ = name_ptr;
    _ = name_len;
    // TODO: lookup singleton by name
    return 0;
}

// ---------------------------------------------------------------------------
// @GlobalScope utility functions
// ---------------------------------------------------------------------------

/// @GlobalScope.sin  hash=2140049587  category=math
/// Roc: Host.util_sin_2140049587!
export fn godot_roc_util_sin_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("sin", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.cos  hash=2140049587  category=math
/// Roc: Host.util_cos_2140049587!
export fn godot_roc_util_cos_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("cos", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.tan  hash=2140049587  category=math
/// Roc: Host.util_tan_2140049587!
export fn godot_roc_util_tan_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("tan", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.sinh  hash=2140049587  category=math
/// Roc: Host.util_sinh_2140049587!
export fn godot_roc_util_sinh_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("sinh", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.cosh  hash=2140049587  category=math
/// Roc: Host.util_cosh_2140049587!
export fn godot_roc_util_cosh_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("cosh", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.tanh  hash=2140049587  category=math
/// Roc: Host.util_tanh_2140049587!
export fn godot_roc_util_tanh_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("tanh", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.asin  hash=2140049587  category=math
/// Roc: Host.util_asin_2140049587!
export fn godot_roc_util_asin_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("asin", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.acos  hash=2140049587  category=math
/// Roc: Host.util_acos_2140049587!
export fn godot_roc_util_acos_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("acos", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.atan  hash=2140049587  category=math
/// Roc: Host.util_atan_2140049587!
export fn godot_roc_util_atan_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("atan", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.atan2  hash=92296394  category=math
/// Roc: Host.util_atan2_92296394!
export fn godot_roc_util_atan2_92296394() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("atan2", 92296394)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.asinh  hash=2140049587  category=math
/// Roc: Host.util_asinh_2140049587!
export fn godot_roc_util_asinh_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("asinh", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.acosh  hash=2140049587  category=math
/// Roc: Host.util_acosh_2140049587!
export fn godot_roc_util_acosh_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("acosh", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.atanh  hash=2140049587  category=math
/// Roc: Host.util_atanh_2140049587!
export fn godot_roc_util_atanh_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("atanh", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.sqrt  hash=2140049587  category=math
/// Roc: Host.util_sqrt_2140049587!
export fn godot_roc_util_sqrt_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("sqrt", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.fmod  hash=92296394  category=math
/// Roc: Host.util_fmod_92296394!
export fn godot_roc_util_fmod_92296394() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("fmod", 92296394)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.fposmod  hash=92296394  category=math
/// Roc: Host.util_fposmod_92296394!
export fn godot_roc_util_fposmod_92296394() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("fposmod", 92296394)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.posmod  hash=3133453818  category=math
/// Roc: Host.util_posmod_3133453818!
export fn godot_roc_util_posmod_3133453818() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("posmod", 3133453818)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.floor  hash=4776452  category=math
/// Roc: Host.util_floor_4776452!
export fn godot_roc_util_floor_4776452() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("floor", 4776452)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.floorf  hash=2140049587  category=math
/// Roc: Host.util_floorf_2140049587!
export fn godot_roc_util_floorf_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("floorf", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.floori  hash=2780425386  category=math
/// Roc: Host.util_floori_2780425386!
export fn godot_roc_util_floori_2780425386() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("floori", 2780425386)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.ceil  hash=4776452  category=math
/// Roc: Host.util_ceil_4776452!
export fn godot_roc_util_ceil_4776452() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("ceil", 4776452)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.ceilf  hash=2140049587  category=math
/// Roc: Host.util_ceilf_2140049587!
export fn godot_roc_util_ceilf_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("ceilf", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.ceili  hash=2780425386  category=math
/// Roc: Host.util_ceili_2780425386!
export fn godot_roc_util_ceili_2780425386() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("ceili", 2780425386)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.round  hash=4776452  category=math
/// Roc: Host.util_round_4776452!
export fn godot_roc_util_round_4776452() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("round", 4776452)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.roundf  hash=2140049587  category=math
/// Roc: Host.util_roundf_2140049587!
export fn godot_roc_util_roundf_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("roundf", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.roundi  hash=2780425386  category=math
/// Roc: Host.util_roundi_2780425386!
export fn godot_roc_util_roundi_2780425386() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("roundi", 2780425386)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.abs  hash=4776452  category=math
/// Roc: Host.util_abs_4776452!
export fn godot_roc_util_abs_4776452() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("abs", 4776452)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.absf  hash=2140049587  category=math
/// Roc: Host.util_absf_2140049587!
export fn godot_roc_util_absf_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("absf", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.absi  hash=2157319888  category=math
/// Roc: Host.util_absi_2157319888!
export fn godot_roc_util_absi_2157319888() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("absi", 2157319888)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.sign  hash=4776452  category=math
/// Roc: Host.util_sign_4776452!
export fn godot_roc_util_sign_4776452() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("sign", 4776452)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.signf  hash=2140049587  category=math
/// Roc: Host.util_signf_2140049587!
export fn godot_roc_util_signf_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("signf", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.signi  hash=2157319888  category=math
/// Roc: Host.util_signi_2157319888!
export fn godot_roc_util_signi_2157319888() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("signi", 2157319888)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.snapped  hash=459914704  category=math
/// Roc: Host.util_snapped_459914704!
export fn godot_roc_util_snapped_459914704() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("snapped", 459914704)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.snappedf  hash=92296394  category=math
/// Roc: Host.util_snappedf_92296394!
export fn godot_roc_util_snappedf_92296394() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("snappedf", 92296394)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.snappedi  hash=3570758393  category=math
/// Roc: Host.util_snappedi_3570758393!
export fn godot_roc_util_snappedi_3570758393() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("snappedi", 3570758393)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.pow  hash=92296394  category=math
/// Roc: Host.util_pow_92296394!
export fn godot_roc_util_pow_92296394() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("pow", 92296394)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.log  hash=2140049587  category=math
/// Roc: Host.util_log_2140049587!
export fn godot_roc_util_log_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("log", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.exp  hash=2140049587  category=math
/// Roc: Host.util_exp_2140049587!
export fn godot_roc_util_exp_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("exp", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.is_nan  hash=3569215213  category=math
/// Roc: Host.util_is_nan_3569215213!
export fn godot_roc_util_is_nan_3569215213() callconv(.c) bool {
    // TODO: variant_get_ptr_utility_function("is_nan", 3569215213)
    // TODO: call with packed arguments from Roc
    return false;
}

/// @GlobalScope.is_inf  hash=3569215213  category=math
/// Roc: Host.util_is_inf_3569215213!
export fn godot_roc_util_is_inf_3569215213() callconv(.c) bool {
    // TODO: variant_get_ptr_utility_function("is_inf", 3569215213)
    // TODO: call with packed arguments from Roc
    return false;
}

/// @GlobalScope.is_equal_approx  hash=1400789633  category=math
/// Roc: Host.util_is_equal_approx_1400789633!
export fn godot_roc_util_is_equal_approx_1400789633() callconv(.c) bool {
    // TODO: variant_get_ptr_utility_function("is_equal_approx", 1400789633)
    // TODO: call with packed arguments from Roc
    return false;
}

/// @GlobalScope.is_zero_approx  hash=3569215213  category=math
/// Roc: Host.util_is_zero_approx_3569215213!
export fn godot_roc_util_is_zero_approx_3569215213() callconv(.c) bool {
    // TODO: variant_get_ptr_utility_function("is_zero_approx", 3569215213)
    // TODO: call with packed arguments from Roc
    return false;
}

/// @GlobalScope.is_finite  hash=3569215213  category=math
/// Roc: Host.util_is_finite_3569215213!
export fn godot_roc_util_is_finite_3569215213() callconv(.c) bool {
    // TODO: variant_get_ptr_utility_function("is_finite", 3569215213)
    // TODO: call with packed arguments from Roc
    return false;
}

/// @GlobalScope.ease  hash=92296394  category=math
/// Roc: Host.util_ease_92296394!
export fn godot_roc_util_ease_92296394() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("ease", 92296394)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.step_decimals  hash=2780425386  category=math
/// Roc: Host.util_step_decimals_2780425386!
export fn godot_roc_util_step_decimals_2780425386() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("step_decimals", 2780425386)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.lerp  hash=3389874542  category=math
/// Roc: Host.util_lerp_3389874542!
export fn godot_roc_util_lerp_3389874542() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("lerp", 3389874542)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.lerpf  hash=998901048  category=math
/// Roc: Host.util_lerpf_998901048!
export fn godot_roc_util_lerpf_998901048() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("lerpf", 998901048)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.cubic_interpolate  hash=1090965791  category=math
/// Roc: Host.util_cubic_interpolate_1090965791!
export fn godot_roc_util_cubic_interpolate_1090965791() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("cubic_interpolate", 1090965791)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.cubic_interpolate_angle  hash=1090965791  category=math
/// Roc: Host.util_cubic_interpolate_angle_1090965791!
export fn godot_roc_util_cubic_interpolate_angle_1090965791() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("cubic_interpolate_angle", 1090965791)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.cubic_interpolate_in_time  hash=388121036  category=math
/// Roc: Host.util_cubic_interpolate_in_time_388121036!
export fn godot_roc_util_cubic_interpolate_in_time_388121036() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("cubic_interpolate_in_time", 388121036)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.cubic_interpolate_angle_in_time  hash=388121036  category=math
/// Roc: Host.util_cubic_interpolate_angle_in_time_388121036!
export fn godot_roc_util_cubic_interpolate_angle_in_time_388121036() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("cubic_interpolate_angle_in_time", 388121036)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.bezier_interpolate  hash=1090965791  category=math
/// Roc: Host.util_bezier_interpolate_1090965791!
export fn godot_roc_util_bezier_interpolate_1090965791() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("bezier_interpolate", 1090965791)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.bezier_derivative  hash=1090965791  category=math
/// Roc: Host.util_bezier_derivative_1090965791!
export fn godot_roc_util_bezier_derivative_1090965791() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("bezier_derivative", 1090965791)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.angle_difference  hash=92296394  category=math
/// Roc: Host.util_angle_difference_92296394!
export fn godot_roc_util_angle_difference_92296394() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("angle_difference", 92296394)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.lerp_angle  hash=998901048  category=math
/// Roc: Host.util_lerp_angle_998901048!
export fn godot_roc_util_lerp_angle_998901048() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("lerp_angle", 998901048)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.inverse_lerp  hash=998901048  category=math
/// Roc: Host.util_inverse_lerp_998901048!
export fn godot_roc_util_inverse_lerp_998901048() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("inverse_lerp", 998901048)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.remap  hash=1090965791  category=math
/// Roc: Host.util_remap_1090965791!
export fn godot_roc_util_remap_1090965791() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("remap", 1090965791)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.smoothstep  hash=998901048  category=math
/// Roc: Host.util_smoothstep_998901048!
export fn godot_roc_util_smoothstep_998901048() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("smoothstep", 998901048)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.move_toward  hash=998901048  category=math
/// Roc: Host.util_move_toward_998901048!
export fn godot_roc_util_move_toward_998901048() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("move_toward", 998901048)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.rotate_toward  hash=998901048  category=math
/// Roc: Host.util_rotate_toward_998901048!
export fn godot_roc_util_rotate_toward_998901048() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("rotate_toward", 998901048)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.deg_to_rad  hash=2140049587  category=math
/// Roc: Host.util_deg_to_rad_2140049587!
export fn godot_roc_util_deg_to_rad_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("deg_to_rad", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.rad_to_deg  hash=2140049587  category=math
/// Roc: Host.util_rad_to_deg_2140049587!
export fn godot_roc_util_rad_to_deg_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("rad_to_deg", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.linear_to_db  hash=2140049587  category=math
/// Roc: Host.util_linear_to_db_2140049587!
export fn godot_roc_util_linear_to_db_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("linear_to_db", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.db_to_linear  hash=2140049587  category=math
/// Roc: Host.util_db_to_linear_2140049587!
export fn godot_roc_util_db_to_linear_2140049587() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("db_to_linear", 2140049587)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.wrap  hash=3389874542  category=math
/// Roc: Host.util_wrap_3389874542!
export fn godot_roc_util_wrap_3389874542() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("wrap", 3389874542)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.wrapi  hash=650295447  category=math
/// Roc: Host.util_wrapi_650295447!
export fn godot_roc_util_wrapi_650295447() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("wrapi", 650295447)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.wrapf  hash=998901048  category=math
/// Roc: Host.util_wrapf_998901048!
export fn godot_roc_util_wrapf_998901048() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("wrapf", 998901048)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.max  hash=3896050336  category=math
/// Roc: Host.util_max_3896050336!
export fn godot_roc_util_max_3896050336() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("max", 3896050336)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.maxi  hash=3133453818  category=math
/// Roc: Host.util_maxi_3133453818!
export fn godot_roc_util_maxi_3133453818() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("maxi", 3133453818)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.maxf  hash=92296394  category=math
/// Roc: Host.util_maxf_92296394!
export fn godot_roc_util_maxf_92296394() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("maxf", 92296394)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.min  hash=3896050336  category=math
/// Roc: Host.util_min_3896050336!
export fn godot_roc_util_min_3896050336() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("min", 3896050336)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.mini  hash=3133453818  category=math
/// Roc: Host.util_mini_3133453818!
export fn godot_roc_util_mini_3133453818() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("mini", 3133453818)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.minf  hash=92296394  category=math
/// Roc: Host.util_minf_92296394!
export fn godot_roc_util_minf_92296394() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("minf", 92296394)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.clamp  hash=3389874542  category=math
/// Roc: Host.util_clamp_3389874542!
export fn godot_roc_util_clamp_3389874542() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("clamp", 3389874542)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.clampi  hash=650295447  category=math
/// Roc: Host.util_clampi_650295447!
export fn godot_roc_util_clampi_650295447() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("clampi", 650295447)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.clampf  hash=998901048  category=math
/// Roc: Host.util_clampf_998901048!
export fn godot_roc_util_clampf_998901048() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("clampf", 998901048)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.nearest_po2  hash=2157319888  category=math
/// Roc: Host.util_nearest_po2_2157319888!
export fn godot_roc_util_nearest_po2_2157319888() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("nearest_po2", 2157319888)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.pingpong  hash=92296394  category=math
/// Roc: Host.util_pingpong_92296394!
export fn godot_roc_util_pingpong_92296394() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("pingpong", 92296394)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.randomize  hash=1691721052  category=random
/// Roc: Host.util_randomize_1691721052!
export fn godot_roc_util_randomize_1691721052() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("randomize", 1691721052)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.randi  hash=701202648  category=random
/// Roc: Host.util_randi_701202648!
export fn godot_roc_util_randi_701202648() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("randi", 701202648)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.randf  hash=2086227845  category=random
/// Roc: Host.util_randf_2086227845!
export fn godot_roc_util_randf_2086227845() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("randf", 2086227845)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.randi_range  hash=3133453818  category=random
/// Roc: Host.util_randi_range_3133453818!
export fn godot_roc_util_randi_range_3133453818() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("randi_range", 3133453818)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.randf_range  hash=92296394  category=random
/// Roc: Host.util_randf_range_92296394!
export fn godot_roc_util_randf_range_92296394() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("randf_range", 92296394)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.randfn  hash=92296394  category=random
/// Roc: Host.util_randfn_92296394!
export fn godot_roc_util_randfn_92296394() callconv(.c) f64 {
    // TODO: variant_get_ptr_utility_function("randfn", 92296394)
    // TODO: call with packed arguments from Roc
    return 0.0;
}

/// @GlobalScope.seed  hash=382931173  category=random
/// Roc: Host.util_seed_382931173!
export fn godot_roc_util_seed_382931173() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("seed", 382931173)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.rand_from_seed  hash=1391063685  category=random
/// Roc: Host.util_rand_from_seed_1391063685!
export fn godot_roc_util_rand_from_seed_1391063685() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("rand_from_seed", 1391063685)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.weakref  hash=4776452  category=general
/// Roc: Host.util_weakref_4776452!
export fn godot_roc_util_weakref_4776452() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("weakref", 4776452)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.typeof  hash=326422594  category=general
/// Roc: Host.util_typeof_326422594!
export fn godot_roc_util_typeof_326422594() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("typeof", 326422594)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.type_convert  hash=2453062746  category=general
/// Roc: Host.util_type_convert_2453062746!
export fn godot_roc_util_type_convert_2453062746() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("type_convert", 2453062746)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.str  hash=32569176  category=general
/// Roc: Host.util_str_32569176!
export fn godot_roc_util_str_32569176() callconv(.c) void /* TODO: RocStr out-param */ {
    // TODO: variant_get_ptr_utility_function("str", 32569176)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.error_string  hash=942708242  category=general
/// Roc: Host.util_error_string_942708242!
export fn godot_roc_util_error_string_942708242() callconv(.c) void /* TODO: RocStr out-param */ {
    // TODO: variant_get_ptr_utility_function("error_string", 942708242)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.type_string  hash=942708242  category=general
/// Roc: Host.util_type_string_942708242!
export fn godot_roc_util_type_string_942708242() callconv(.c) void /* TODO: RocStr out-param */ {
    // TODO: variant_get_ptr_utility_function("type_string", 942708242)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.print  hash=2648703342  category=general
/// Roc: Host.util_print_2648703342!
export fn godot_roc_util_print_2648703342() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("print", 2648703342)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.print_rich  hash=2648703342  category=general
/// Roc: Host.util_print_rich_2648703342!
export fn godot_roc_util_print_rich_2648703342() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("print_rich", 2648703342)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.printerr  hash=2648703342  category=general
/// Roc: Host.util_printerr_2648703342!
export fn godot_roc_util_printerr_2648703342() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("printerr", 2648703342)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.printt  hash=2648703342  category=general
/// Roc: Host.util_printt_2648703342!
export fn godot_roc_util_printt_2648703342() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("printt", 2648703342)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.prints  hash=2648703342  category=general
/// Roc: Host.util_prints_2648703342!
export fn godot_roc_util_prints_2648703342() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("prints", 2648703342)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.printraw  hash=2648703342  category=general
/// Roc: Host.util_printraw_2648703342!
export fn godot_roc_util_printraw_2648703342() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("printraw", 2648703342)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.print_verbose  hash=2648703342  category=general
/// Roc: Host.util_print_verbose_2648703342!
export fn godot_roc_util_print_verbose_2648703342() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("print_verbose", 2648703342)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.push_error  hash=2648703342  category=general
/// Roc: Host.util_push_error_2648703342!
export fn godot_roc_util_push_error_2648703342() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("push_error", 2648703342)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.push_warning  hash=2648703342  category=general
/// Roc: Host.util_push_warning_2648703342!
export fn godot_roc_util_push_warning_2648703342() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("push_warning", 2648703342)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.var_to_str  hash=866625479  category=general
/// Roc: Host.util_var_to_str_866625479!
export fn godot_roc_util_var_to_str_866625479() callconv(.c) void /* TODO: RocStr out-param */ {
    // TODO: variant_get_ptr_utility_function("var_to_str", 866625479)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.str_to_var  hash=1891498491  category=general
/// Roc: Host.util_str_to_var_1891498491!
export fn godot_roc_util_str_to_var_1891498491() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("str_to_var", 1891498491)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.var_to_bytes  hash=2947269930  category=general
/// Roc: Host.util_var_to_bytes_2947269930!
export fn godot_roc_util_var_to_bytes_2947269930() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("var_to_bytes", 2947269930)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.bytes_to_var  hash=4249819452  category=general
/// Roc: Host.util_bytes_to_var_4249819452!
export fn godot_roc_util_bytes_to_var_4249819452() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("bytes_to_var", 4249819452)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.var_to_bytes_with_objects  hash=2947269930  category=general
/// Roc: Host.util_var_to_bytes_with_objects_2947269930!
export fn godot_roc_util_var_to_bytes_with_objects_2947269930() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("var_to_bytes_with_objects", 2947269930)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.bytes_to_var_with_objects  hash=4249819452  category=general
/// Roc: Host.util_bytes_to_var_with_objects_4249819452!
export fn godot_roc_util_bytes_to_var_with_objects_4249819452() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("bytes_to_var_with_objects", 4249819452)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.hash  hash=326422594  category=general
/// Roc: Host.util_hash_326422594!
export fn godot_roc_util_hash_326422594() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("hash", 326422594)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.instance_from_id  hash=1156694636  category=general
/// Roc: Host.util_instance_from_id_1156694636!
export fn godot_roc_util_instance_from_id_1156694636() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("instance_from_id", 1156694636)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.is_instance_id_valid  hash=2232439758  category=general
/// Roc: Host.util_is_instance_id_valid_2232439758!
export fn godot_roc_util_is_instance_id_valid_2232439758() callconv(.c) bool {
    // TODO: variant_get_ptr_utility_function("is_instance_id_valid", 2232439758)
    // TODO: call with packed arguments from Roc
    return false;
}

/// @GlobalScope.is_instance_valid  hash=996128841  category=general
/// Roc: Host.util_is_instance_valid_996128841!
export fn godot_roc_util_is_instance_valid_996128841() callconv(.c) bool {
    // TODO: variant_get_ptr_utility_function("is_instance_valid", 996128841)
    // TODO: call with packed arguments from Roc
    return false;
}

/// @GlobalScope.rid_allocate_id  hash=701202648  category=general
/// Roc: Host.util_rid_allocate_id_701202648!
export fn godot_roc_util_rid_allocate_id_701202648() callconv(.c) i64 {
    // TODO: variant_get_ptr_utility_function("rid_allocate_id", 701202648)
    // TODO: call with packed arguments from Roc
    return 0;
}

/// @GlobalScope.rid_from_int64  hash=3426892196  category=general
/// Roc: Host.util_rid_from_int64_3426892196!
export fn godot_roc_util_rid_from_int64_3426892196() callconv(.c) void {
    // TODO: variant_get_ptr_utility_function("rid_from_int64", 3426892196)
    // TODO: call with packed arguments from Roc
    return ;
}

/// @GlobalScope.is_same  hash=1409423524  category=general
/// Roc: Host.util_is_same_1409423524!
export fn godot_roc_util_is_same_1409423524() callconv(.c) bool {
    // TODO: variant_get_ptr_utility_function("is_same", 1409423524)
    // TODO: call with packed arguments from Roc
    return false;
}

// ---------------------------------------------------------------------------
// Example class method pattern (CharacterBody3D) — copy for Host.<m>_<hash>!
// ---------------------------------------------------------------------------

// var g_mb_move_and_slide: ?*anyopaque = null;
//
// export fn godot_roc_move_and_slide() callconv(.c) void {
//     // ensureMethodBinds();
//     // const self = requireCurrent() orelse return;
//     // ptrcall(g_mb_move_and_slide, self.object, null, ...);
// }

// export fn godot_roc_input_is_action_pressed(/* action: RocStr */) callconv(.c) u8 {
//     var buf: [64]u8 = undefined;
//     // const z = rocStrToZ(action, &buf) orelse return 0;
//     // return if (isActionPressed(z)) 1 else 0;
//     return 0;
// }
