name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  full-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main  # optional, speeds cache

      - name: CI inside flake
        run: nix develop -c roc run scripts/ci.roc
        # or: nix develop -c bin/ci
        # or a flake app: nix run .#ci
